<a href="https://colab.research.google.com/github/sakshi13s/sakshi-book-recommender-project/blob/main/Book_Recommender_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#importing the 3 dataset of books, users and book ratings
!gdown https://drive.google.com/uc?id=16b-VgOnuvFI047G1cFlNU3GPf4z0il7f
!unzip Books.csv.zip

Downloading...
From: https://drive.google.com/uc?id=16b-VgOnuvFI047G1cFlNU3GPf4z0il7f
To: /content/Books.csv.zip
100% 15.6M/15.6M [00:00<00:00, 37.0MB/s]
Archive:  Books.csv.zip
  inflating: Books.csv

In [2]:
!gdown https://drive.google.com/uc?id=1zJuz4mGvYuV1gSTXTeNTfjUP4FH4b8OU
!unzip Users.csv.zip

Downloading...
From: https://drive.google.com/uc?id=1zJuz4mGvYuV1gSTXTeNTfjUP4FH4b8OU
To: /content/Users.csv.zip
100% 2.98M/2.98M [00:00<00:00, 193MB/s]
Archive:  Users.csv.zip
  inflating: Users.csv

In [3]:
!gdown https://drive.google.com/uc?id=1_RzfJ7NvrWcrVLFTkKId6DfxS6f9wHfT
!unzip Ratings.csv.zip

Downloading...
From: https://drive.google.com/uc?id=1_RzfJ7NvrWcrVLFTkKId6DfxS6f9wHfT
To: /content/Ratings.csv.zip
100% 6.41M/6.41M [00:00<00:00, 18.0MB/s]
Archive:  Ratings.csv.zip
  inflating: Ratings.csv

In [4]:
import numpy as np
import pandas as pd

In [5]:
books = pd.read_csv('Books.csv')

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [6]:
#books dataframe
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [7]:
books.shape

(271360, 8)

In [8]:
users = pd.read_csv('Users.csv')

In [9]:
#users dataframe
users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [10]:
users.shape

(278858, 3)

In [11]:
ratings = pd.read_csv('Ratings.csv')

In [12]:
#ratings dataframe
ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [13]:
ratings.shape

(1149780, 3)

In [14]:
books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            1
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [15]:
books.duplicated().sum()

0

In [16]:
#finding missing values but age is not required for recommendation
users.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [17]:
users.duplicated().sum()

0

In [18]:
ratings.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [19]:
ratings.duplicated().sum()

0

## Popularity Based (Best Sellers)

In [20]:
#merge ratings and books dataframe on the basis of ISBN
ratings.merge(books, on='ISBN')

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,2313,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
2,6543,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
3,8680,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
4,10314,034545104X,9,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
...,...,...,...,...,...,...,...,...,...,...
1031131,276688,0517145553,0,Mostly Harmless,Douglas Adams,1995,Random House Value Pub,http://images.amazon.com/images/P/0517145553.0...,http://images.amazon.com/images/P/0517145553.0...,http://images.amazon.com/images/P/0517145553.0...
1031132,276688,1575660792,7,Gray Matter,Shirley Kennett,1996,Kensington Publishing Corporation,http://images.amazon.com/images/P/1575660792.0...,http://images.amazon.com/images/P/1575660792.0...,http://images.amazon.com/images/P/1575660792.0...
1031133,276690,0590907301,0,Triplet Trouble and the Class Trip (Triplet Tr...,Debbie Dadey,1997,Apple,http://images.amazon.com/images/P/0590907301.0...,http://images.amazon.com/images/P/0590907301.0...,http://images.amazon.com/images/P/0590907301.0...
1031134,276704,0679752714,0,A Desert of Pure Feeling (Vintage Contemporaries),Judith Freeman,1997,Vintage Books USA,http://images.amazon.com/images/P/0679752714.0...,http://images.amazon.com/images/P/0679752714.0...,http://images.amazon.com/images/P/0679752714.0...
1031135,276704,0806917695,5,Perplexing Lateral Thinking Puzzles: Scholasti...,Paul Sloane,1997,Sterling Publishing,http://images.amazon.com/images/P/0806917695.0...,http://images.amazon.com/images/P/0806917695.0...,http://images.amazon.com/images/P/0806917695.0...

In [21]:
ratings.merge(books, on='ISBN').shape

(1031136, 10)

In [22]:
#storing the new dataframe in a new variable
ratings_with_bookname = ratings.merge(books, on='ISBN')

In [23]:
ratings_with_bookname

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,2313,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
2,6543,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
3,8680,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
4,10314,034545104X,9,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
...,...,...,...,...,...,...,...,...,...,...
1031131,276688,0517145553,0,Mostly Harmless,Douglas Adams,1995,Random House Value Pub,http://images.amazon.com/images/P/0517145553.0...,http://images.amazon.com/images/P/0517145553.0...,http://images.amazon.com/images/P/0517145553.0...
1031132,276688,1575660792,7,Gray Matter,Shirley Kennett,1996,Kensington Publishing Corporation,http://images.amazon.com/images/P/1575660792.0...,http://images.amazon.com/images/P/1575660792.0...,http://images.amazon.com/images/P/1575660792.0...
1031133,276690,0590907301,0,Triplet Trouble and the Class Trip (Triplet Tr...,Debbie Dadey,1997,Apple,http://images.amazon.com/images/P/0590907301.0...,http://images.amazon.com/images/P/0590907301.0...,http://images.amazon.com/images/P/0590907301.0...
1031134,276704,0679752714,0,A Desert of Pure Feeling (Vintage Contemporaries),Judith Freeman,1997,Vintage Books USA,http://images.amazon.com/images/P/0679752714.0...,http://images.amazon.com/images/P/0679752714.0...,http://images.amazon.com/images/P/0679752714.0...
1031135,276704,0806917695,5,Perplexing Lateral Thinking Puzzles: Scholasti...,Paul Sloane,1997,Sterling Publishing,http://images.amazon.com/images/P/0806917695.0...,http://images.amazon.com/images/P/0806917695.0...,http://images.amazon.com/images/P/0806917695.0...

In [24]:
#to find the avg votes and consider only those books which have number of ratings >250
ratings_with_bookname.groupby('Book-Title').count()

,User-ID,ISBN,Book-Rating,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
Book-Title,,,,,,,,,
"A Light in the Storm: The Civil War Diary of Amelia Martin, Fenwick Island, Delaware, 1861 (Dear America)",4,4,4,4,4,4,4,4,4
Always Have Popsicles,1,1,1,1,1,1,1,1,1
Apple Magic (The Collector's series),1,1,1,1,1,1,1,1,1
"Ask Lily (Young Women of Faith: Lily Series, Book 5)",1,1,1,1,1,1,1,1,1
Beyond IBM: Leadership Marketing and Finance for the 1990s,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...
Ã?Â?lpiraten.,2,2,2,2,2,2,2,2,2
Ã?Â?rger mit Produkt X. Roman.,4,4,4,4,4,4,4,4,4
Ã?Â?sterlich leben.,1,1,1,1,1,1,1,1,1
Ã?Â?stlich der Berge.,3,3,3,3,3,3,3,3,3
Ã?Â?thique en toc,2,2,2,2,2,2,2,2,2

In [25]:
ratings_with_bookname.groupby('Book-Title').count()['Book-Rating']

Book-Title
 A Light in the Storm: The Civil War Diary of Amelia Martin, Fenwick Island, Delaware, 1861 (Dear America)    4
 Always Have Popsicles                                                                                        1
 Apple Magic (The Collector's series)                                                                         1
 Ask Lily (Young Women of Faith: Lily Series, Book 5)                                                         1
 Beyond IBM: Leadership Marketing and Finance for the 1990s                                                   1
                                                                                                             ..
Ã?Â?lpiraten.                                                                                                 2
Ã?Â?rger mit Produkt X. Roman.                                                                                4
Ã?Â?sterlich leben.                                                                                           1
Ã?Â?stlich der Berge.                                                                                         3
Ã?Â?thique en toc                                                                                             2
Name: Book-Rating, Length: 241071, dtype: int64

In [26]:
ratings_with_bookname.groupby('Book-Title').count()['Book-Rating'].reset_index()

                                               Book-Title  Book-Rating
0        A Light in the Storm: The Civil War Diary of ...            4
1                                   Always Have Popsicles            1
2                    Apple Magic (The Collector's series)            1
3        Ask Lily (Young Women of Faith: Lily Series, ...            1
4        Beyond IBM: Leadership Marketing and Finance ...            1
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.            2
241067                     Ã?Â?rger mit Produkt X. Roman.            4
241068                                Ã?Â?sterlich leben.            1
241069                              Ã?Â?stlich der Berge.            3
241070                                  Ã?Â?thique en toc            2

[241071 rows x 2 columns]

In [27]:
#new dataframe
num_rating_df = ratings_with_bookname.groupby('Book-Title').count()['Book-Rating'].reset_index()

In [28]:
num_rating_df.rename(columns={'Book-Rating': 'num_of_ratings'}, inplace=True)

In [29]:
num_rating_df

                                               Book-Title  num_of_ratings
0        A Light in the Storm: The Civil War Diary of ...               4
1                                   Always Have Popsicles               1
2                    Apple Magic (The Collector's series)               1
3        Ask Lily (Young Women of Faith: Lily Series, ...               1
4        Beyond IBM: Leadership Marketing and Finance ...               1
...                                                   ...             ...
241066                                      Ã?Â?lpiraten.               2
241067                     Ã?Â?rger mit Produkt X. Roman.               4
241068                                Ã?Â?sterlich leben.               1
241069                              Ã?Â?stlich der Berge.               3
241070                                  Ã?Â?thique en toc               2

[241071 rows x 2 columns]

In [30]:
#dataframe which contains avg rating of books
avg_rating_df = ratings_with_bookname.groupby('Book-Title').mean()['Book-Rating'].reset_index()

In [31]:
avg_rating_df.rename(columns={'Book-Rating': 'avg_ratings'}, inplace=True)

In [32]:
avg_rating_df

                                               Book-Title  avg_ratings
0        A Light in the Storm: The Civil War Diary of ...     2.250000
1                                   Always Have Popsicles     0.000000
2                    Apple Magic (The Collector's series)     0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...     8.000000
4        Beyond IBM: Leadership Marketing and Finance ...     0.000000
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.     0.000000
241067                     Ã?Â?rger mit Produkt X. Roman.     5.250000
241068                                Ã?Â?sterlich leben.     7.000000
241069                              Ã?Â?stlich der Berge.     2.666667
241070                                  Ã?Â?thique en toc     4.000000

[241071 rows x 2 columns]

In [33]:
popular_df = num_rating_df.merge(avg_rating_df, on='Book-Title')

In [34]:
popular_df

,Book-Title,num_of_ratings,avg_ratings
0,A Light in the Storm: The Civil War Diary of ...,4,2.250000
1,Always Have Popsicles,1,0.000000
2,Apple Magic (The Collector's series),1,0.000000
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,8.000000
4,Beyond IBM: Leadership Marketing and Finance ...,1,0.000000
...,...,...,...
241066,Ã?Â?lpiraten.,2,0.000000
241067,Ã?Â?rger mit Produkt X. Roman.,4,5.250000
241068,Ã?Â?sterlich leben.,1,7.000000
241069,Ã?Â?stlich der Berge.,3,2.666667
241070,Ã?Â?thique en toc,2,4.000000

In [35]:
#considering only those books which have a minimum rating of 250
popular_df[popular_df['num_of_ratings']>=250]

,Book-Title,num_of_ratings,avg_ratings
764,1984,284,4.454225
818,1st to Die: A Novel,509,3.575639
1048,2nd Chance,356,3.269663
1760,A Bend in the Road,346,3.364162
2281,"A Child Called \It\"": One Child's Courage to S...",265,4.086792
...,...,...,...
233850,White Oleander : A Novel,387,3.506460
233851,White Oleander : A Novel (Oprah's Book Club),356,3.772472
234740,Wicked: The Life and Times of the Wicked Witch...,326,3.766871
234951,Wild Animus,2502,1.019584
240860,"\O\"" Is for Outlaw""",269,2.988848

In [36]:
popular_df[popular_df['num_of_ratings']>=250].sort_values('avg_ratings', ascending=False)

,Book-Title,num_of_ratings,avg_ratings
80434,Harry Potter and the Prisoner of Azkaban (Book 3),428,5.852804
80422,Harry Potter and the Goblet of Fire (Book 4),387,5.824289
80441,Harry Potter and the Sorcerer's Stone (Book 1),278,5.737410
80426,Harry Potter and the Order of the Phoenix (Boo...,347,5.501441
80414,Harry Potter and the Chamber of Secrets (Book 2),556,5.183453
...,...,...,...
227701,Vinegar Hill (Oprah's Book Club (Paperback)),265,2.245283
233635,Whispers,286,2.199301
143377,Presumed Innocent,294,2.139456
94382,Isle of Dogs,288,2.000000
234951,Wild Animus,2502,1.019584

In [37]:
#getting top 21 most popular books
popular_df[popular_df['num_of_ratings']>=250].sort_values('avg_ratings', ascending=False).head(21)

,Book-Title,num_of_ratings,avg_ratings
80434,Harry Potter and the Prisoner of Azkaban (Book 3),428,5.852804
80422,Harry Potter and the Goblet of Fire (Book 4),387,5.824289
80441,Harry Potter and the Sorcerer's Stone (Book 1),278,5.737410
80426,Harry Potter and the Order of the Phoenix (Boo...,347,5.501441
80414,Harry Potter and the Chamber of Secrets (Book 2),556,5.183453
191612,The Hobbit : The Enchanting Prelude to The Lor...,281,5.007117
187377,The Fellowship of the Ring (The Lord of the Ri...,368,4.948370
80445,Harry Potter and the Sorcerer's Stone (Harry P...,575,4.895652
211384,"The Two Towers (The Lord of the Rings, Part 2)",260,4.880769
219741,To Kill a Mockingbird,510,4.700000
183573,The Da Vinci Code,898,4.642539
187880,The Five People You Meet in Heaven,430,4.551163
180556,The Catcher in the Rye,449,4.545657
196326,The Lovely Bones: A Novel,1295,4.468726
764,1984,284,4.454225
144165,Prodigal Summer: A Novel,253,4.450593
128670,Neverwhere,265,4.449057
206502,The Secret Life of Bees,774,4.447028
168719,Stupid White Men ...and Other Sorry Excuses fo...,283,4.356890
223135,"Tuesdays with Morrie: An Old Man, a Young Man,...",493,4.354970
204387,The Red Tent (Bestselling Backlist),723,4.334716

In [38]:
popular_df = popular_df[popular_df['num_of_ratings']>=250].sort_values('avg_ratings', ascending=False).head(21)

In [39]:
popular_df

,Book-Title,num_of_ratings,avg_ratings
80434,Harry Potter and the Prisoner of Azkaban (Book 3),428,5.852804
80422,Harry Potter and the Goblet of Fire (Book 4),387,5.824289
80441,Harry Potter and the Sorcerer's Stone (Book 1),278,5.737410
80426,Harry Potter and the Order of the Phoenix (Boo...,347,5.501441
80414,Harry Potter and the Chamber of Secrets (Book 2),556,5.183453
191612,The Hobbit : The Enchanting Prelude to The Lor...,281,5.007117
187377,The Fellowship of the Ring (The Lord of the Ri...,368,4.948370
80445,Harry Potter and the Sorcerer's Stone (Harry P...,575,4.895652
211384,"The Two Towers (The Lord of the Rings, Part 2)",260,4.880769
219741,To Kill a Mockingbird,510,4.700000
183573,The Da Vinci Code,898,4.642539
187880,The Five People You Meet in Heaven,430,4.551163
180556,The Catcher in the Rye,449,4.545657
196326,The Lovely Bones: A Novel,1295,4.468726
764,1984,284,4.454225
144165,Prodigal Summer: A Novel,253,4.450593
128670,Neverwhere,265,4.449057
206502,The Secret Life of Bees,774,4.447028
168719,Stupid White Men ...and Other Sorry Excuses fo...,283,4.356890
223135,"Tuesdays with Morrie: An Old Man, a Young Man,...",493,4.354970
204387,The Red Tent (Bestselling Backlist),723,4.334716

In [40]:
popular_df.merge(books, on='Book-Title')

,Book-Title,num_of_ratings,avg_ratings,ISBN,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,Harry Potter and the Prisoner of Azkaban (Book 3),428,5.852804,0439136350,J. K. Rowling,1999,Scholastic,http://images.amazon.com/images/P/0439136350.0...,http://images.amazon.com/images/P/0439136350.0...,http://images.amazon.com/images/P/0439136350.0...
1,Harry Potter and the Prisoner of Azkaban (Book 3),428,5.852804,0439136369,J. K. Rowling,2001,Scholastic,http://images.amazon.com/images/P/0439136369.0...,http://images.amazon.com/images/P/0439136369.0...,http://images.amazon.com/images/P/0439136369.0...
2,Harry Potter and the Prisoner of Azkaban (Book 3),428,5.852804,0786222743,J. K. Rowling,2000,Thorndike Press,http://images.amazon.com/images/P/0786222743.0...,http://images.amazon.com/images/P/0786222743.0...,http://images.amazon.com/images/P/0786222743.0...
3,Harry Potter and the Goblet of Fire (Book 4),387,5.824289,0439139597,J. K. Rowling,2000,Scholastic,http://images.amazon.com/images/P/0439139597.0...,http://images.amazon.com/images/P/0439139597.0...,http://images.amazon.com/images/P/0439139597.0...
4,Harry Potter and the Goblet of Fire (Book 4),387,5.824289,0439139600,J. K. Rowling,2002,Scholastic Paperbacks,http://images.amazon.com/images/P/0439139600.0...,http://images.amazon.com/images/P/0439139600.0...,http://images.amazon.com/images/P/0439139600.0...
...,...,...,...,...,...,...,...,...,...,...
84,Stupid White Men ...and Other Sorry Excuses fo...,283,4.356890,0060392452,Michael Moore,2002,Regan Books,http://images.amazon.com/images/P/0060392452.0...,http://images.amazon.com/images/P/0060392452.0...,http://images.amazon.com/images/P/0060392452.0...
85,"Tuesdays with Morrie: An Old Man, a Young Man,...",493,4.354970,0385484518,MITCH ALBOM,1997,Doubleday,http://images.amazon.com/images/P/0385484518.0...,http://images.amazon.com/images/P/0385484518.0...,http://images.amazon.com/images/P/0385484518.0...
86,"Tuesdays with Morrie: An Old Man, a Young Man,...",493,4.354970,076790592X,Mitch Albom,2002,Broadway,http://images.amazon.com/images/P/076790592X.0...,http://images.amazon.com/images/P/076790592X.0...,http://images.amazon.com/images/P/076790592X.0...
87,"Tuesdays with Morrie: An Old Man, a Young Man,...",493,4.354970,076790592x,Mitch Albom,2002,Broadway,http://images.amazon.com/images/P/076790592X.0...,http://images.amazon.com/images/P/076790592X.0...,http://images.amazon.com/images/P/076790592X.0...
88,The Red Tent (Bestselling Backlist),723,4.334716,0312195516,Anita Diamant,1998,Picador USA,http://images.amazon.com/images/P/0312195516.0...,http://images.amazon.com/images/P/0312195516.0...,http://images.amazon.com/images/P/0312195516.0...

In [41]:
popular_df.merge(books, on='Book-Title').drop_duplicates('Book-Title')

,Book-Title,num_of_ratings,avg_ratings,ISBN,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,Harry Potter and the Prisoner of Azkaban (Book 3),428,5.852804,0439136350,J. K. Rowling,1999,Scholastic,http://images.amazon.com/images/P/0439136350.0...,http://images.amazon.com/images/P/0439136350.0...,http://images.amazon.com/images/P/0439136350.0...
3,Harry Potter and the Goblet of Fire (Book 4),387,5.824289,0439139597,J. K. Rowling,2000,Scholastic,http://images.amazon.com/images/P/0439139597.0...,http://images.amazon.com/images/P/0439139597.0...,http://images.amazon.com/images/P/0439139597.0...
5,Harry Potter and the Sorcerer's Stone (Book 1),278,5.737410,0590353403,J. K. Rowling,1998,Scholastic,http://images.amazon.com/images/P/0590353403.0...,http://images.amazon.com/images/P/0590353403.0...,http://images.amazon.com/images/P/0590353403.0...
9,Harry Potter and the Order of the Phoenix (Boo...,347,5.501441,043935806X,J. K. Rowling,2003,Scholastic,http://images.amazon.com/images/P/043935806X.0...,http://images.amazon.com/images/P/043935806X.0...,http://images.amazon.com/images/P/043935806X.0...
13,Harry Potter and the Chamber of Secrets (Book 2),556,5.183453,0439064872,J. K. Rowling,2000,Scholastic,http://images.amazon.com/images/P/0439064872.0...,http://images.amazon.com/images/P/0439064872.0...,http://images.amazon.com/images/P/0439064872.0...
16,The Hobbit : The Enchanting Prelude to The Lor...,281,5.007117,0345339681,J.R.R. TOLKIEN,1986,Del Rey,http://images.amazon.com/images/P/0345339681.0...,http://images.amazon.com/images/P/0345339681.0...,http://images.amazon.com/images/P/0345339681.0...
17,The Fellowship of the Ring (The Lord of the Ri...,368,4.948370,0345339703,J.R.R. TOLKIEN,1986,Del Rey,http://images.amazon.com/images/P/0345339703.0...,http://images.amazon.com/images/P/0345339703.0...,http://images.amazon.com/images/P/0345339703.0...
26,Harry Potter and the Sorcerer's Stone (Harry P...,575,4.895652,059035342X,J. K. Rowling,1999,Arthur A. Levine Books,http://images.amazon.com/images/P/059035342X.0...,http://images.amazon.com/images/P/059035342X.0...,http://images.amazon.com/images/P/059035342X.0...
28,"The Two Towers (The Lord of the Rings, Part 2)",260,4.880769,0345339711,J.R.R. TOLKIEN,1986,Del Rey,http://images.amazon.com/images/P/0345339711.0...,http://images.amazon.com/images/P/0345339711.0...,http://images.amazon.com/images/P/0345339711.0...
39,To Kill a Mockingbird,510,4.700000,0446310786,Harper Lee,1988,Little Brown &amp; Company,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...
47,The Da Vinci Code,898,4.642539,0385504209,Dan Brown,2003,Doubleday,http://images.amazon.com/images/P/0385504209.0...,http://images.amazon.com/images/P/0385504209.0...,http://images.amazon.com/images/P/0385504209.0...
53,The Five People You Meet in Heaven,430,4.551163,0786868716,Mitch Albom,2003,Hyperion,http://images.amazon.com/images/P/0786868716.0...,http://images.amazon.com/images/P/0786868716.0...,http://images.amazon.com/images/P/0786868716.0...
55,The Catcher in the Rye,449,4.545657,0316769487,J.D. Salinger,1991,"Little, Brown",http://images.amazon.com/images/P/0316769487.0...,http://images.amazon.com/images/P/0316769487.0...,http://images.amazon.com/images/P/0316769487.0...
62,The Lovely Bones: A Novel,1295,4.468726,0316666343,Alice Sebold,2002,"Little, Brown",http://images.amazon.com/images/P/0316666343.0...,http://images.amazon.com/images/P/0316666343.0...,http://images.amazon.com/images/P/0316666343.0...
63,1984,284,4.454225,0451524934,George Orwell,1990,Signet Book,http://images.amazon.com/images/P/0451524934.0...,http://images.amazon.com/images/P/0451524934.0...,http://images.amazon.com/images/P/0451524934.0...
72,Prodigal Summer: A Novel,253,4.450593,0060959037,Barbara Kingsolver,2001,Perennial,http://images.amazon.com/images/P/0060959037.0...,http://images.amazon.com/images/P/0060959037.0...,http://images.amazon.com/images/P/0060959037.0...
73,Neverwhere,265,4.449057,0380789019,Neil Gaiman,1998,Avon,http://images.amazon.com/images/P/0380789019.0...,http://images.amazon.com/images/P/0380789019.0...,http://images.amazon.com/images/P/0380789019.0...
78,The Secret Life of Bees,774,4.447028,0142001740,Sue Monk Kidd,2003,Penguin Books,http://images.amazon.com/images/P/0142001740.0...,http://images.amazon.com/images/P/0142001740.0...,http://images.amazon.com/images/P/0142001740.0...
84,Stupid White Men ...and Other Sorry Excuses fo...,283,4.356890,0060392452,Michael Moore,2002,Regan Books,http://images.amazon.com/images/P/0060392452.0...,http://images.amazon.com/images/P/0060392452.0...,http://images.amazon.com/images/P/0060392452.0...
85,"Tuesdays with Morrie: An Old Man, a Young Man,...",493,4.354970,0385484518,MITCH ALBOM,1997,Doubleday,http://images.amazon.com/images/P/0385484518.0...,http://images.amazon.com/images/P/0385484518.0...,http://images.amazon.com/images/P/0385484518.0...
88,The Red Tent (Bestselling Backlist),723,4.334716,0312195516,Anita Diamant,1998,Picador USA,http://images.amazon.com/images/P/0312195516.0...,http://images.amazon.com/images/P/0312195516.0...,http://images.amazon.com/images/P/0312195516.0...

In [42]:
popular_df.merge(books, on='Book-Title').drop_duplicates('Book-Title').shape

(21, 10)

In [43]:
popular_df.merge(books, on='Book-Title').drop_duplicates('Book-Title')[['Book-Title', 'Book-Author', 'Image-URL-M', 'num_of_ratings', 'avg_ratings']]

,Book-Title,Book-Author,Image-URL-M,num_of_ratings,avg_ratings
0,Harry Potter and the Prisoner of Azkaban (Book 3),J. K. Rowling,http://images.amazon.com/images/P/0439136350.0...,428,5.852804
3,Harry Potter and the Goblet of Fire (Book 4),J. K. Rowling,http://images.amazon.com/images/P/0439139597.0...,387,5.824289
5,Harry Potter and the Sorcerer's Stone (Book 1),J. K. Rowling,http://images.amazon.com/images/P/0590353403.0...,278,5.737410
9,Harry Potter and the Order of the Phoenix (Boo...,J. K. Rowling,http://images.amazon.com/images/P/043935806X.0...,347,5.501441
13,Harry Potter and the Chamber of Secrets (Book 2),J. K. Rowling,http://images.amazon.com/images/P/0439064872.0...,556,5.183453
16,The Hobbit : The Enchanting Prelude to The Lor...,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339681.0...,281,5.007117
17,The Fellowship of the Ring (The Lord of the Ri...,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339703.0...,368,4.948370
26,Harry Potter and the Sorcerer's Stone (Harry P...,J. K. Rowling,http://images.amazon.com/images/P/059035342X.0...,575,4.895652
28,"The Two Towers (The Lord of the Rings, Part 2)",J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339711.0...,260,4.880769
39,To Kill a Mockingbird,Harper Lee,http://images.amazon.com/images/P/0446310786.0...,510,4.700000
47,The Da Vinci Code,Dan Brown,http://images.amazon.com/images/P/0385504209.0...,898,4.642539
53,The Five People You Meet in Heaven,Mitch Albom,http://images.amazon.com/images/P/0786868716.0...,430,4.551163
55,The Catcher in the Rye,J.D. Salinger,http://images.amazon.com/images/P/0316769487.0...,449,4.545657
62,The Lovely Bones: A Novel,Alice Sebold,http://images.amazon.com/images/P/0316666343.0...,1295,4.468726
63,1984,George Orwell,http://images.amazon.com/images/P/0451524934.0...,284,4.454225
72,Prodigal Summer: A Novel,Barbara Kingsolver,http://images.amazon.com/images/P/0060959037.0...,253,4.450593
73,Neverwhere,Neil Gaiman,http://images.amazon.com/images/P/0380789019.0...,265,4.449057
78,The Secret Life of Bees,Sue Monk Kidd,http://images.amazon.com/images/P/0142001740.0...,774,4.447028
84,Stupid White Men ...and Other Sorry Excuses fo...,Michael Moore,http://images.amazon.com/images/P/0060392452.0...,283,4.356890
85,"Tuesdays with Morrie: An Old Man, a Young Man,...",MITCH ALBOM,http://images.amazon.com/images/P/0385484518.0...,493,4.354970
88,The Red Tent (Bestselling Backlist),Anita Diamant,http://images.amazon.com/images/P/0312195516.0...,723,4.334716

In [44]:
popular_df = popular_df.merge(books, on='Book-Title').drop_duplicates('Book-Title')[['Book-Title', 'Book-Author', 'Image-URL-M', 'num_of_ratings', 'avg_ratings']]

In [45]:
popular_df

,Book-Title,Book-Author,Image-URL-M,num_of_ratings,avg_ratings
0,Harry Potter and the Prisoner of Azkaban (Book 3),J. K. Rowling,http://images.amazon.com/images/P/0439136350.0...,428,5.852804
3,Harry Potter and the Goblet of Fire (Book 4),J. K. Rowling,http://images.amazon.com/images/P/0439139597.0...,387,5.824289
5,Harry Potter and the Sorcerer's Stone (Book 1),J. K. Rowling,http://images.amazon.com/images/P/0590353403.0...,278,5.737410
9,Harry Potter and the Order of the Phoenix (Boo...,J. K. Rowling,http://images.amazon.com/images/P/043935806X.0...,347,5.501441
13,Harry Potter and the Chamber of Secrets (Book 2),J. K. Rowling,http://images.amazon.com/images/P/0439064872.0...,556,5.183453
16,The Hobbit : The Enchanting Prelude to The Lor...,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339681.0...,281,5.007117
17,The Fellowship of the Ring (The Lord of the Ri...,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339703.0...,368,4.948370
26,Harry Potter and the Sorcerer's Stone (Harry P...,J. K. Rowling,http://images.amazon.com/images/P/059035342X.0...,575,4.895652
28,"The Two Towers (The Lord of the Rings, Part 2)",J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339711.0...,260,4.880769
39,To Kill a Mockingbird,Harper Lee,http://images.amazon.com/images/P/0446310786.0...,510,4.700000
47,The Da Vinci Code,Dan Brown,http://images.amazon.com/images/P/0385504209.0...,898,4.642539
53,The Five People You Meet in Heaven,Mitch Albom,http://images.amazon.com/images/P/0786868716.0...,430,4.551163
55,The Catcher in the Rye,J.D. Salinger,http://images.amazon.com/images/P/0316769487.0...,449,4.545657
62,The Lovely Bones: A Novel,Alice Sebold,http://images.amazon.com/images/P/0316666343.0...,1295,4.468726
63,1984,George Orwell,http://images.amazon.com/images/P/0451524934.0...,284,4.454225
72,Prodigal Summer: A Novel,Barbara Kingsolver,http://images.amazon.com/images/P/0060959037.0...,253,4.450593
73,Neverwhere,Neil Gaiman,http://images.amazon.com/images/P/0380789019.0...,265,4.449057
78,The Secret Life of Bees,Sue Monk Kidd,http://images.amazon.com/images/P/0142001740.0...,774,4.447028
84,Stupid White Men ...and Other Sorry Excuses fo...,Michael Moore,http://images.amazon.com/images/P/0060392452.0...,283,4.356890
85,"Tuesdays with Morrie: An Old Man, a Young Man,...",MITCH ALBOM,http://images.amazon.com/images/P/0385484518.0...,493,4.354970
88,The Red Tent (Bestselling Backlist),Anita Diamant,http://images.amazon.com/images/P/0312195516.0...,723,4.334716

In [46]:
popular_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 21 entries, 0 to 88
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Book-Title      21 non-null     object
 1   Book-Author     21 non-null     object
 2   Image-URL-M     21 non-null     object
 3   num_of_ratings  21 non-null     int64
 4   avg_ratings     21 non-null     float64
dtypes: float64(1), int64(1), object(3)
memory usage: 1008.0+ bytes

## Collaborative Filtering Based

In [47]:
ratings_with_bookname

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,2313,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
2,6543,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
3,8680,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
4,10314,034545104X,9,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
...,...,...,...,...,...,...,...,...,...,...
1031131,276688,0517145553,0,Mostly Harmless,Douglas Adams,1995,Random House Value Pub,http://images.amazon.com/images/P/0517145553.0...,http://images.amazon.com/images/P/0517145553.0...,http://images.amazon.com/images/P/0517145553.0...
1031132,276688,1575660792,7,Gray Matter,Shirley Kennett,1996,Kensington Publishing Corporation,http://images.amazon.com/images/P/1575660792.0...,http://images.amazon.com/images/P/1575660792.0...,http://images.amazon.com/images/P/1575660792.0...
1031133,276690,0590907301,0,Triplet Trouble and the Class Trip (Triplet Tr...,Debbie Dadey,1997,Apple,http://images.amazon.com/images/P/0590907301.0...,http://images.amazon.com/images/P/0590907301.0...,http://images.amazon.com/images/P/0590907301.0...
1031134,276704,0679752714,0,A Desert of Pure Feeling (Vintage Contemporaries),Judith Freeman,1997,Vintage Books USA,http://images.amazon.com/images/P/0679752714.0...,http://images.amazon.com/images/P/0679752714.0...,http://images.amazon.com/images/P/0679752714.0...
1031135,276704,0806917695,5,Perplexing Lateral Thinking Puzzles: Scholasti...,Paul Sloane,1997,Sterling Publishing,http://images.amazon.com/images/P/0806917695.0...,http://images.amazon.com/images/P/0806917695.0...,http://images.amazon.com/images/P/0806917695.0...

In [48]:
#to get information about which user has rated how many books
ratings_with_bookname.groupby('User-ID').count()

,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
User-ID,,,,,,,,,
2,1,1,1,1,1,1,1,1,1
8,17,17,17,17,17,17,17,17,17
9,3,3,3,3,3,3,3,3,3
10,1,1,1,1,1,1,1,1,1
12,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...
278846,1,1,1,1,1,1,1,1,1
278849,4,4,4,4,4,4,4,4,4
278851,23,23,23,23,23,23,23,23,23
278852,1,1,1,1,1,1,1,1,1
278854,8,8,8,8,8,8,8,8,8

In [49]:
ratings_with_bookname.groupby('User-ID').count()['Book-Rating']

User-ID
2          1
8         17
9          3
10         1
12         1
          ..
278846     1
278849     4
278851    23
278852     1
278854     8
Name: Book-Rating, Length: 92106, dtype: int64

In [51]:
#considering only those users who have rated more than 200 books
ratings_with_bookname.groupby('User-ID').count()['Book-Rating'] > 200

User-ID
2         False
8         False
9         False
10        False
12        False
          ...
278846    False
278849    False
278851    False
278852    False
278854    False
Name: Book-Rating, Length: 92106, dtype: bool

In [52]:
x = ratings_with_bookname.groupby('User-ID').count()['Book-Rating'] > 200

In [53]:
x[x]

User-ID
254       True
2276      True
2766      True
2977      True
3363      True
          ...
274308    True
275970    True
277427    True
277639    True
278418    True
Name: Book-Rating, Length: 811, dtype: bool

In [54]:
x[x].index

Int64Index([   254,   2276,   2766,   2977,   3363,   4017,   4385,   6251,
              6323,   6543,
            ...
            271705, 273979, 274004, 274061, 274301, 274308, 275970, 277427,
            277639, 278418],
           dtype='int64', name='User-ID', length=811)

In [55]:
y = x[x].index

In [56]:
ratings_with_bookname['User-ID'].isin(y)

0          False
1          False
2           True
3          False
4          False
           ...
1031131    False
1031132    False
1031133    False
1031134    False
1031135    False
Name: User-ID, Length: 1031136, dtype: bool

In [57]:
ratings_with_bookname[ratings_with_bookname['User-ID'].isin(y)]

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
2,6543,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
5,23768,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
7,28523,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
15,77940,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
16,81977,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
...,...,...,...,...,...,...,...,...,...,...
1030883,275970,1880837927,0,The Theology of the Hammer,Millard Fuller,1994,Smyth &amp; Helwys Publishing,http://images.amazon.com/images/P/1880837927.0...,http://images.amazon.com/images/P/1880837927.0...,http://images.amazon.com/images/P/1880837927.0...
1030884,275970,188717897X,0,The Ordeal of Integration: Progress and Resent...,Orlando Patterson,1998,Civitas Book Publisher,http://images.amazon.com/images/P/188717897X.0...,http://images.amazon.com/images/P/188717897X.0...,http://images.amazon.com/images/P/188717897X.0...
1030885,275970,1888889047,0,Pushcart's Complete Rotten Reviews &amp; Rejec...,Bill Henderson,1998,Pushcart Press,http://images.amazon.com/images/P/1888889047.0...,http://images.amazon.com/images/P/1888889047.0...,http://images.amazon.com/images/P/1888889047.0...
1030886,275970,1931868123,0,There's a Porcupine in My Outhouse: Misadventu...,Mike Tougias,2002,Capital Books (VA),http://images.amazon.com/images/P/1931868123.0...,http://images.amazon.com/images/P/1931868123.0...,http://images.amazon.com/images/P/1931868123.0...
1030887,275970,3411086211,10,Die Biene.,Sybil GrÃ?Â¤fin SchÃ?Â¶nfeldt,1993,"Bibliographisches Institut, Mannheim",http://images.amazon.com/images/P/3411086211.0...,http://images.amazon.com/images/P/3411086211.0...,http://images.amazon.com/images/P/3411086211.0...

In [58]:
filtered_rating = ratings_with_bookname[ratings_with_bookname['User-ID'].isin(y)]

In [59]:
filtered_rating

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
2,6543,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
5,23768,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
7,28523,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
15,77940,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
16,81977,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
...,...,...,...,...,...,...,...,...,...,...
1030883,275970,1880837927,0,The Theology of the Hammer,Millard Fuller,1994,Smyth &amp; Helwys Publishing,http://images.amazon.com/images/P/1880837927.0...,http://images.amazon.com/images/P/1880837927.0...,http://images.amazon.com/images/P/1880837927.0...
1030884,275970,188717897X,0,The Ordeal of Integration: Progress and Resent...,Orlando Patterson,1998,Civitas Book Publisher,http://images.amazon.com/images/P/188717897X.0...,http://images.amazon.com/images/P/188717897X.0...,http://images.amazon.com/images/P/188717897X.0...
1030885,275970,1888889047,0,Pushcart's Complete Rotten Reviews &amp; Rejec...,Bill Henderson,1998,Pushcart Press,http://images.amazon.com/images/P/1888889047.0...,http://images.amazon.com/images/P/1888889047.0...,http://images.amazon.com/images/P/1888889047.0...
1030886,275970,1931868123,0,There's a Porcupine in My Outhouse: Misadventu...,Mike Tougias,2002,Capital Books (VA),http://images.amazon.com/images/P/1931868123.0...,http://images.amazon.com/images/P/1931868123.0...,http://images.amazon.com/images/P/1931868123.0...
1030887,275970,3411086211,10,Die Biene.,Sybil GrÃ?Â¤fin SchÃ?Â¶nfeldt,1993,"Bibliographisches Institut, Mannheim",http://images.amazon.com/images/P/3411086211.0...,http://images.amazon.com/images/P/3411086211.0...,http://images.amazon.com/images/P/3411086211.0...

In [60]:
filtered_rating.groupby('Book-Title').count()['Book-Rating']

Book-Title
 A Light in the Storm: The Civil War Diary of Amelia Martin, Fenwick Island, Delaware, 1861 (Dear America)    2
 Always Have Popsicles                                                                                        1
 Apple Magic (The Collector's series)                                                                         1
 Beyond IBM: Leadership Marketing and Finance for the 1990s                                                   1
 Clifford Visita El Hospital (Clifford El Gran Perro Colorado)                                                1
                                                                                                             ..
Ã?Â?ber das Fernsehen.                                                                                        2
Ã?Â?ber die Pflicht zum Ungehorsam gegen den Staat.                                                           3
Ã?Â?lpiraten.                                                                                                 1
Ã?Â?stlich der Berge.                                                                                         1
Ã?Â?thique en toc                                                                                             1
Name: Book-Rating, Length: 155845, dtype: int64

In [61]:
filtered_rating.groupby('Book-Title').count()['Book-Rating'] >=50

Book-Title
 A Light in the Storm: The Civil War Diary of Amelia Martin, Fenwick Island, Delaware, 1861 (Dear America)    False
 Always Have Popsicles                                                                                        False
 Apple Magic (The Collector's series)                                                                         False
 Beyond IBM: Leadership Marketing and Finance for the 1990s                                                   False
 Clifford Visita El Hospital (Clifford El Gran Perro Colorado)                                                False
                                                                                                              ...
Ã?Â?ber das Fernsehen.                                                                                        False
Ã?Â?ber die Pflicht zum Ungehorsam gegen den Staat.                                                           False
Ã?Â?lpiraten.                                                                                                 False
Ã?Â?stlich der Berge.                                                                                         False
Ã?Â?thique en toc                                                                                             False
Name: Book-Rating, Length: 155845, dtype: bool

In [62]:
z = filtered_rating.groupby('Book-Title').count()['Book-Rating'] >=50

In [63]:
z[z]

Book-Title
1984                                                                 True
1st to Die: A Novel                                                  True
2nd Chance                                                           True
4 Blondes                                                            True
A Bend in the Road                                                   True
                                                                     ...
Year of Wonders                                                      True
You Belong To Me                                                     True
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values    True
Zoya                                                                 True
\O\" Is for Outlaw"                                                  True
Name: Book-Rating, Length: 706, dtype: bool

In [64]:
famous_books = z[z].index

In [65]:
famous_books

Index(['1984', '1st to Die: A Novel', '2nd Chance', '4 Blondes',
       'A Bend in the Road', 'A Case of Need',
       'A Child Called \It\": One Child's Courage to Survive"',
       'A Civil Action', 'A Day Late and a Dollar Short', 'A Fine Balance',
       ...
       'Winter Solstice', 'Wish You Well', 'Without Remorse',
       'Wizard and Glass (The Dark Tower, Book 4)', 'Wuthering Heights',
       'Year of Wonders', 'You Belong To Me',
       'Zen and the Art of Motorcycle Maintenance: An Inquiry into Values',
       'Zoya', '\O\" Is for Outlaw"'],
      dtype='object', name='Book-Title', length=706)

In [66]:
filtered_rating['Book-Title'].isin(famous_books)

2          False
5          False
7          False
15         False
16         False
           ...
1030883    False
1030884    False
1030885    False
1030886    False
1030887    False
Name: Book-Title, Length: 474007, dtype: bool

In [67]:
filtered_rating[filtered_rating['Book-Title'].isin(famous_books)]

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
63,278418,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
65,3363,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
66,7158,0446520802,10,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
69,11676,0446520802,10,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
74,23768,0446520802,6,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
...,...,...,...,...,...,...,...,...,...,...
1026724,266865,0531001725,10,The Catcher in the Rye,Jerome David Salinger,1973,Scholastic Library Pub,http://images.amazon.com/images/P/0531001725.0...,http://images.amazon.com/images/P/0531001725.0...,http://images.amazon.com/images/P/0531001725.0...
1027923,269566,0670809381,0,Echoes,Maeve Binchy,1986,Penguin USA,http://images.amazon.com/images/P/0670809381.0...,http://images.amazon.com/images/P/0670809381.0...,http://images.amazon.com/images/P/0670809381.0...
1028777,271284,0440910927,0,The Rainmaker,John Grisham,1995,Island,http://images.amazon.com/images/P/0440910927.0...,http://images.amazon.com/images/P/0440910927.0...,http://images.amazon.com/images/P/0440910927.0...
1029070,271705,B0001PIOX4,0,Fahrenheit 451,Ray Bradbury,1993,Simon &amp; Schuster,http://images.amazon.com/images/P/B0001PIOX4.0...,http://images.amazon.com/images/P/B0001PIOX4.0...,http://images.amazon.com/images/P/B0001PIOX4.0...
1030868,275970,1586210661,9,Me Talk Pretty One Day,David Sedaris,2001,Time Warner Audio Major,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...

In [68]:
final_ratings = filtered_rating[filtered_rating['Book-Title'].isin(famous_books)]

In [69]:
final_ratings

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
63,278418,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
65,3363,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
66,7158,0446520802,10,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
69,11676,0446520802,10,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
74,23768,0446520802,6,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
...,...,...,...,...,...,...,...,...,...,...
1026724,266865,0531001725,10,The Catcher in the Rye,Jerome David Salinger,1973,Scholastic Library Pub,http://images.amazon.com/images/P/0531001725.0...,http://images.amazon.com/images/P/0531001725.0...,http://images.amazon.com/images/P/0531001725.0...
1027923,269566,0670809381,0,Echoes,Maeve Binchy,1986,Penguin USA,http://images.amazon.com/images/P/0670809381.0...,http://images.amazon.com/images/P/0670809381.0...,http://images.amazon.com/images/P/0670809381.0...
1028777,271284,0440910927,0,The Rainmaker,John Grisham,1995,Island,http://images.amazon.com/images/P/0440910927.0...,http://images.amazon.com/images/P/0440910927.0...,http://images.amazon.com/images/P/0440910927.0...
1029070,271705,B0001PIOX4,0,Fahrenheit 451,Ray Bradbury,1993,Simon &amp; Schuster,http://images.amazon.com/images/P/B0001PIOX4.0...,http://images.amazon.com/images/P/B0001PIOX4.0...,http://images.amazon.com/images/P/B0001PIOX4.0...
1030868,275970,1586210661,9,Me Talk Pretty One Day,David Sedaris,2001,Time Warner Audio Major,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...

In [70]:
final_ratings.drop_duplicates()

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
63,278418,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
65,3363,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
66,7158,0446520802,10,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
69,11676,0446520802,10,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
74,23768,0446520802,6,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
...,...,...,...,...,...,...,...,...,...,...
1026724,266865,0531001725,10,The Catcher in the Rye,Jerome David Salinger,1973,Scholastic Library Pub,http://images.amazon.com/images/P/0531001725.0...,http://images.amazon.com/images/P/0531001725.0...,http://images.amazon.com/images/P/0531001725.0...
1027923,269566,0670809381,0,Echoes,Maeve Binchy,1986,Penguin USA,http://images.amazon.com/images/P/0670809381.0...,http://images.amazon.com/images/P/0670809381.0...,http://images.amazon.com/images/P/0670809381.0...
1028777,271284,0440910927,0,The Rainmaker,John Grisham,1995,Island,http://images.amazon.com/images/P/0440910927.0...,http://images.amazon.com/images/P/0440910927.0...,http://images.amazon.com/images/P/0440910927.0...
1029070,271705,B0001PIOX4,0,Fahrenheit 451,Ray Bradbury,1993,Simon &amp; Schuster,http://images.amazon.com/images/P/B0001PIOX4.0...,http://images.amazon.com/images/P/B0001PIOX4.0...,http://images.amazon.com/images/P/B0001PIOX4.0...
1030868,275970,1586210661,9,Me Talk Pretty One Day,David Sedaris,2001,Time Warner Audio Major,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...

In [71]:
final_ratings.pivot_table(index = 'Book-Title', columns = 'User-ID', values = 'Book-Rating')

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
1st to Die: A Novel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2nd Chance,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN
4 Blondes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A Bend in the Road,0.0,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,9.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
You Belong To Me,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
Zoya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"\O\"" Is for Outlaw""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN

In [72]:
pt = final_ratings.pivot_table(index = 'Book-Title', columns = 'User-ID', values = 'Book-Rating')

In [73]:
pt

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
1st to Die: A Novel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2nd Chance,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN
4 Blondes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A Bend in the Road,0.0,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,9.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
You Belong To Me,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
Zoya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"\O\"" Is for Outlaw""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN

In [74]:
pt.fillna(0, inplace=True)

In [75]:
pt

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Bend in the Road,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0

In [76]:
from sklearn.metrics.pairwise import cosine_similarity

In [77]:
cosine_similarity(pt)

array([[1.        , 0.10255025, 0.01220856, ..., 0.12110367, 0.07347567,
        0.04316046],
       [0.10255025, 1.        , 0.2364573 , ..., 0.07446129, 0.16773875,
        0.14263397],
       [0.01220856, 0.2364573 , 1.        , ..., 0.04558758, 0.04938579,
        0.10796119],
       ...,
       [0.12110367, 0.07446129, 0.04558758, ..., 1.        , 0.07085128,
        0.0196177 ],
       [0.07347567, 0.16773875, 0.04938579, ..., 0.07085128, 1.        ,
        0.10602962],
       [0.04316046, 0.14263397, 0.10796119, ..., 0.0196177 , 0.10602962,
        1.        ]])

In [78]:
cosine_similarity(pt).shape

(706, 706)

In [79]:
similarity_scores = cosine_similarity(pt)

In [80]:
similarity_scores

array([[1.        , 0.10255025, 0.01220856, ..., 0.12110367, 0.07347567,
        0.04316046],
       [0.10255025, 1.        , 0.2364573 , ..., 0.07446129, 0.16773875,
        0.14263397],
       [0.01220856, 0.2364573 , 1.        , ..., 0.04558758, 0.04938579,
        0.10796119],
       ...,
       [0.12110367, 0.07446129, 0.04558758, ..., 1.        , 0.07085128,
        0.0196177 ],
       [0.07347567, 0.16773875, 0.04938579, ..., 0.07085128, 1.        ,
        0.10602962],
       [0.04316046, 0.14263397, 0.10796119, ..., 0.0196177 , 0.10602962,
        1.        ]])

In [81]:
similarity_scores.shape

(706, 706)

In [82]:
def recommend(book_name):
  # fetch index
  return suggestions

In [83]:
np.where(pt.index=='4 Blondes')

(array([3]),)

In [84]:
np.where(pt.index=='4 Blondes')[0][0]

3

In [85]:
def recommend(book_name):
  # fetch index
  index = np.where(pt.index== book_name)[0][0]
  distances = similarity_scores[index]
  return suggestions

In [86]:
similarity_scores[3]

array([0.        , 0.        , 0.        , 1.        , 0.        ,
       0.11158235, 0.        , 0.        , 0.07439555, 0.        ,
       0.        , 0.14576203, 0.05499338, 0.        , 0.        ,
       0.        , 0.        , 0.04289816, 0.        , 0.11215379,
       0.        , 0.        , 0.02473898, 0.        , 0.0254068 ,
       0.12305174, 0.        , 0.        , 0.        , 0.        ,
       0.09381049, 0.        , 0.06859607, 0.        , 0.0779401 ,
       0.03771542, 0.08134518, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.05477141, 0.        , 0.05958855,
       0.        , 0.        , 0.07684047, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.06703391,
       0.        , 0.        , 0.03245271, 0.        , 0.0408861 ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.0094036 , 0.        , 0.        , 0.00939554, 0.        ,
       0.        , 0.        , 0.        , 0.00945087, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.01391526, 0.        , 0.08376125, 0.        , 0.        ,
       0.        , 0.        , 0.13135471, 0.17154711, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.04600352, 0.        , 0.05049882, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.05043018,
       0.        , 0.10676555, 0.05710297, 0.01066106, 0.        ,
       0.        , 0.08575255, 0.06960268, 0.00912889, 0.        ,
       0.        , 0.05441552, 0.        , 0.03913303, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.01440697, 0.        , 0.        , 0.12004349, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.0272477 , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.12334016, 0.        , 0.        , 0.00956496, 0.        ,
       0.        , 0.03990103, 0.14343389, 0.        , 0.        ,
       0.04560018, 0.06717621, 0.10647205, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.09259924, 0.06387072,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.04320058, 0.        , 0.01905907, 0.07076543,
       0.        , 0.        , 0.00955608, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.12883478, 0.06979597, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.06184529, 0.        , 0.        , 0.        ,
       0.        , 0.07890729, 0.        , 0.        , 0.03151186,
       0.09868722, 0.09922711, 0.        , 0.11398463, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.00731979, 0.        , 0.08500151, 0.04228386,
       0.04304939, 0.0523528 , 0.        , 0.0814672 , 0.07937953,
       0.10513545, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.1488746 , 0.10506086, 0.        , 0.09415231,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.03707166, 0.        , 0.0891433 , 0.        ,
       0.05545546, 0.        , 0.        , 0.        , 0.        ,
       0.06332714, 0.        , 0.0412574 , 0.        , 0.        ,
       0.04811093, 0.00845878, 0.        , 0.        , 0.        ,
       0.04757652, 0.        , 0.        , 0.10491215, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.0392045 ,
       0.        , 0.04991736, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.09514653, 0.02815089, 0.        ,
       0.        , 0.        , 0.        , 0.11887355, 0.        ,
       0.        , 0.04907322, 0.        , 0.        , 0.        ,
       0.        , 0.11840184, 0.08608478, 0.        , 0.        ,
       0.        , 0.07837604, 0.06118933, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.02930631, 0.        ,
       0.        , 0.        , 0.14284952, 0.06750414, 0.        ,
       0.        , 0.        , 0.03625535, 0.03924103, 0.        ,
       0.        , 0.        , 0.0118392 , 0.        , 0.        ,
       0.        , 0.05619894, 0.08016503, 0.        , 0.0571244 ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.08985299, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.17173795, 0.        ,
       0.13237924, 0.00934346, 0.        , 0.04385491, 0.        ,
       0.        , 0.        , 0.        , 0.06077196, 0.        ,
       0.09678465, 0.        , 0.03294921, 0.01218133, 0.        ,
       0.        , 0.09655285, 0.        , 0.18082023, 0.        ,
       0.03096698, 0.        , 0.        , 0.        , 0.13583222,
       0.        , 0.11320984, 0.        , 0.        , 0.19281549,
       0.12950201, 0.        , 0.0538561 , 0.        , 0.        ,
       0.        , 0.11529596, 0.13520967, 0.03530103, 0.05833565,
       0.        , 0.        , 0.08270159, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.10434075, 0.        , 0.        , 0.080029  , 0.        ,
       0.        , 0.        , 0.16338132, 0.        , 0.        ,
       0.17982397, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.07149048, 0.        , 0.        , 0.07343662,
       0.012991  , 0.        , 0.06441866, 0.        , 0.        ,
       0.03800051, 0.        , 0.12113804, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.0892645 , 0.        ,
       0.        , 0.        , 0.        , 0.0186227 , 0.        ,
       0.        , 0.        , 0.04428181, 0.06261255, 0.        ,
       0.        , 0.04532712, 0.00941595, 0.03716325, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.0438688 , 0.08001838,
       0.06395111, 0.        , 0.        , 0.        , 0.        ,
       0.06109947, 0.06033541, 0.        , 0.        , 0.13638741,
       0.        , 0.1206014 , 0.        , 0.        , 0.13903237,
       0.0715168 , 0.        , 0.04737058, 0.07345872, 0.        ,
       0.05275083, 0.        , 0.06508571, 0.        , 0.        ,
       0.        , 0.13186636, 0.02110099, 0.        , 0.        ,
       0.        , 0.02328199, 0.02966354, 0.        , 0.        ,
       0.        , 0.14774674, 0.        , 0.        , 0.08744402,
       0.        , 0.        , 0.        , 0.06819965, 0.        ,
       0.06155462, 0.        , 0.        , 0.        , 0.        ,
       0.00938315, 0.12707201, 0.        , 0.        , 0.12726645,
       0.        , 0.09144571, 0.04450014, 0.        , 0.01026363,
       0.04124866, 0.        , 0.00868606, 0.        , 0.        ,
       0.07261226, 0.        , 0.        , 0.21653837, 0.11565017,
       0.        , 0.01068115, 0.        , 0.0669917 , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.06533776, 0.        , 0.        , 0.07274018, 0.        ,
       0.06030866, 0.07154773, 0.        , 0.        , 0.        ,
       0.        , 0.15044465, 0.        , 0.07894739, 0.02455742,
       0.06606221, 0.        , 0.02132214, 0.        , 0.        ,
       0.        , 0.06338858, 0.        , 0.        , 0.05785883,
       0.        , 0.0152785 , 0.        , 0.07198303, 0.01012946,
       0.02616119, 0.08277692, 0.09782603, 0.07587245, 0.        ,
       0.01101878, 0.        , 0.03814519, 0.        , 0.        ,
       0.        , 0.02726329, 0.12173922, 0.04951189, 0.        ,
       0.        , 0.0699969 , 0.        , 0.        , 0.        ,
       0.09616416, 0.07840325, 0.        , 0.        , 0.0943043 ,
       0.02710462, 0.        , 0.01086701, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.06194181, 0.06321971,
       0.        , 0.        , 0.        , 0.05856949, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.07223443, 0.        , 0.        ,
       0.09678655, 0.        , 0.        , 0.06191258, 0.        ,
       0.        , 0.        , 0.0411626 , 0.        , 0.        ,
       0.05156192, 0.        , 0.11258865, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.05758506, 0.        ,
       0.        , 0.02976597, 0.        , 0.12265144, 0.        ,
       0.03847017, 0.        , 0.        , 0.        , 0.        ,
       0.07726781, 0.        , 0.        , 0.06925589, 0.07256944,
       0.07672358, 0.        , 0.        , 0.        , 0.03348088,
       0.04574178, 0.12634133, 0.07134425, 0.10735806, 0.0211341 ,
       0.        , 0.        , 0.        , 0.        , 0.01194782,
       0.12348608, 0.10863774, 0.0762425 , 0.        , 0.        ,
       0.        ])

In [87]:
list(enumerate(similarity_scores[0]))

[(0, 0.9999999999999999),
 (1, 0.10255024829874465),
 (2, 0.012208555646509366),
 (3, 0.0),
 (4, 0.053672244225442485),
 (5, 0.027749013024662858),
 (6, 0.08216491130000354),
 (7, 0.13732869060263378),
 (8, 0.03261686350494277),
 (9, 0.03667590746512177),
 (10, 0.02322418425912186),
 (11, 0.06766486753662343),
 (12, 0.020839782065795794),
 (13, 0.09673734976610586),
 (14, 0.13388864701187034),
 (15, 0.08303111691811028),
 (16, 0.1115354275858341),
 (17, 0.05100410510067514),
 (18, 0.025177841632809915),
 (19, 0.11706383185253948),
 (20, 0.0),
 (21, 0.14333792815336935),
 (22, 0.07847534327232125),
 (23, 0.06150451339525138),
 (24, 0.08723968326958673),
 (25, 0.0),
 (26, 0.07009814362931202),
 (27, 0.13658680855472938),
 (28, 0.07600327535501016),
 (29, 0.12167133598776536),
 (30, 0.007680459111722776),
 (31, 0.01473221255132234),
 (32, 0.0),
 (33, 0.07965814289647455),
 (34, 0.04522616573040869),
 (35, 0.01556270914112474),
 (36, 0.09495937740802216),
 (37, 0.018230696811058135),
 (38, 0.026104653172312028),
 (39, 0.07984012108659384),
 (40, 0.11679968613719667),
 (41, 0.056912401804646934),
 (42, 0.08354155383339157),
 (43, 0.08471898090442946),
 (44, 0.08785938150991274),
 (45, 0.05491435163039676),
 (46, 0.054850498513470236),
 (47, 0.2702651417103732),
 (48, 0.09779122591837026),
 (49, 0.060160461842087495),
 (50, 0.08958834926611466),
 (51, 0.06748675491514017),
 (52, 0.0),
 (53, 0.044680983219421905),
 (54, 0.019208718234636258),
 (55, 0.0),
 (56, 0.056290668459108455),
 (57, 0.005579638588454276),
 (58, 0.07877058635507732),
 (59, 0.052194792200893965),
 (60, 0.18908176672188648),
 (61, 0.0),
 (62, 0.012406560213354146),
 (63, 0.029845724311982225),
 (64, 0.04279501979786338),
 (65, 0.12680124740531368),
 (66, 0.16566734565340113),
 (67, 0.0),
 (68, 0.13357242093379193),
 (69, 0.06615478064452682),
 (70, 0.0),
 (71, 0.0),
 (72, 0.0),
 (73, 0.1096807501418389),
 (74, 0.02806606106883051),
 (75, 0.04521795287053612),
 (76, 0.02613276804655889),
 (77, 0.06876130890656589),
 (78, 0.013316271087745269),
 (79, 0.10519138203342883),
 (80, 0.03349456939792139),
 (81, 0.013634576553468258),
 (82, 0.2366937434740099),
 (83, 0.0),
 (84, 0.1039794092420736),
 (85, 0.06167753120046458),
 (86, 0.1417627291694863),
 (87, 0.11661082872914152),
 (88, 0.08331012208964668),
 (89, 0.00850895140653615),
 (90, 0.06715432766232284),
 (91, 0.0),
 (92, 0.1585082118281064),
 (93, 0.03280520241000348),
 (94, 0.010689154840164533),
 (95, 0.025797824097510556),
 (96, 0.02114858980511902),
 (97, 0.02687778911799567),
 (98, 0.02175821065382328),
 (99, 0.0),
 (100, 0.016016629607635186),
 (101, 0.12114265984279052),
 (102, 0.04768602689229997),
 (103, 0.058191840680734276),
 (104, 0.06510721558252526),
 (105, 0.0),
 (106, 0.047670497142785574),
 (107, 0.05273164983675109),
 (108, 0.02810009706063171),
 (109, 0.06524573363186935),
 (110, 0.021163446843373374),
 (111, 0.02097867986921867),
 (112, 0.07422249010392888),
 (113, 0.017527779718968118),
 (114, 0.03734566872286401),
 (115, 0.0),
 (116, 0.01579666260459111),
 (117, 0.1103944810687539),
 (118, 0.165272766123669),
 (119, 0.15514318804365945),
 (120, 0.06237453600241552),
 (121, 0.08139488796880032),
 (122, 0.056554138733275305),
 (123, 0.07458202717929566),
 (124, 0.03771888280719047),
 (125, 0.059363300295016304),
 (126, 0.02955369248311012),
 (127, 0.03355602562283),
 (128, 0.04734092759216691),
 (129, 0.010066425112509755),
 (130, 0.016719816747289874),
 (131, 0.07258934796997447),
 (132, 0.0),
 (133, 0.0),
 (134, 0.0),
 (135, 0.02428501142412964),
 (136, 0.030678189040978528),
 (137, 0.09974980034668829),
 (138, 0.0),
 (139, 0.016901518597837405),
 (140, 0.024108621631248803),
 (141, 0.028108399645259814),
 (142, 0.0),
 (143, 0.0),
 (144, 0.0181287703514146),
 (145, 0.028808272598853126),
 (146, 0.0),
 (147, 0.05995157134958024),
 (148, 0.021276714965680187),
 (149, 0.10341190148072846),
 (150, 0.027667475691473428),
 (151, 0.10684794535545848),
 (152, 0.09898722239993361),
 (153, 0.1414518615569236),
 (154, 0.05007429159938883),
 (155, 0.09428288870384942),
 (156, 0.014112489355409683),
 (157, 0.0),
 (158, 0.07835976130061303),
 (159, 0.00882242400686552),
 (160, 0.04515898041752436),
 (161, 0.0),
 (162, 0.012814117802391826),
 (163, 0.04003333547158616),
 (164, 0.07477661367406771),
 (165, 0.012179056920074677),
 (166, 0.018873932015163516),
 (167, 0.026674838717939867),
 (168, 0.01432863977616057),
 (169, 0.1470284656227732),
 (170, 0.06087281632872059),
 (171, 0.025783211586063344),
 (172, 0.027418756526771074),
 (173, 0.0),
 (174, 0.14909595195082756),
 (175, 0.05606788035530558),
 (176, 0.0),
 (177, 0.03199916313406436),
 (178, 0.03643816906953526),
 (179, 0.0),
 (180, 0.01962921144060071),
 (181, 0.22222254415660225),
 (182, 0.015158449197584845),
 (183, 0.09673267751838878),
 (184, 0.02190023295408395),
 (185, 0.020135489410098205),
 (186, 0.05400331245399732),
 (187, 0.07262017448772083),
 (188, 0.011116365315772406),
 (189, 0.036498718026030004),
 (190, 0.05994663767295999),
 (191, 0.0),
 (192, 0.14691166711955864),
 (193, 0.020860053643757807),
 (194, 0.1035963528100001),
 (195, 0.09794374510256892),
 (196, 0.06609996896203728),
 (197, 0.12871083086643306),
 (198, 0.08992738703666601),
 (199, 0.011474570339750256),
 (200, 0.024601653277066596),
 (201, 0.0),
 (202, 0.18049207281616433),
 (203, 0.05141892092902459),
 (204, 0.047717402129725514),
 (205, 0.10849696385128584),
 (206, 0.13278139031675887),
 (207, 0.059152881703632795),
 (208, 0.053729841666378134),
 (209, 0.034785003361519164),
 (210, 0.0),
 (211, 0.09203038690315052),
 (212, 0.06388401351716998),
 (213, 0.04773328410790857),
 (214, 0.15570975499937129),
 (215, 0.08420691059370962),
 (216, 0.12338216998991305),
 (217, 0.08784690368235953),
 (218, 0.0820594460339464),
 (219, 0.12177532243608828),
 (220, 0.024337026385897676),
 (221, 0.00272862336930817),
 (222, 0.0),
 (223, 0.0),
 (224, 0.03671505063990275),
 (225, 0.1528098402276361),
 (226, 0.03709430441334803),
 (227, 0.07458136399603107),
 (228, 0.09746696979819942),
 (229, 0.05416091103251691),
 (230, 0.10266993316420167),
 (231, 0.0757441443938586),
 (232, 0.06426525769208898),
 (233, 0.03601739518550193),
 (234, 0.01559751952620105),
 (235, 0.02033558874805688),
 (236, 0.024635927968282654),
 (237, 0.0),
 (238, 0.03349154464789058),
 (239, 0.021353685011361416),
 (240, 0.019033695446023926),
 (241, 0.06806264765162154),
 (242, 0.020321161226731627),
 (243, 0.11784705785247843),
 (244, 0.07839488163675291),
 (245, 0.08422557655984436),
 (246, 0.0),
 (247, 0.02040796206066411),
 (248, 0.0),
 (249, 0.046982457315643385),
 (250, 0.08294512991462386),
 (251, 0.13974513728492968),
 (252, 0.012345246102533871),
 (253, 0.13510607638008787),
 (254, 0.07423488726781508),
 (255, 0.11841889291663141),
 (256, 0.049300912125160704),
 (257, 0.016216682151444957),
 (258, 0.026330228561191004),
 (259, 0.04815971759587031),
 (260, 0.019598256153707194),
 (261, 0.10174252819190155),
 (262, 0.13257638388225185),
 (263, 0.0),
 (264, 0.055102704646119355),
 (265, 0.018611497829688243),
 (266, 0.0),
 (267, 0.04504597870526374),
 (268, 0.03482458685305275),
 (269, 0.1650329228149958),
 (270, 0.08466191294337998),
 (271, 0.06795352889900172),
 (272, 0.029876534978291205),
 (273, 0.0),
 (274, 0.0),
 (275, 0.08781992709390865),
 (276, 0.07885279086963545),
 (277, 0.04799058127298857),
 (278, 0.014679640011206505),
 (279, 0.021238372796229556),
 (280, 0.04549923467689111),
 (281, 0.08673968616705958),
 (282, 0.00885998445194921),
 (283, 0.028806369616477166),
 (284, 0.020221447157344582),
 (285, 0.024141217209915328),
 (286, 0.12548312467838352),
 (287, 0.0),
 (288, 0.02482518222135733),
 (289, 0.06520605980064662),
 (290, 0.0),
 (291, 0.06069830203664196),
 (292, 0.011778242975805127),
 (293, 0.13974104783917973),
 (294, 0.019788442258843547),
 (295, 0.012608239194211564),
 (296, 0.08608600626732467),
 (297, 0.04433882752568145),
 (298, 0.029430847399312027),
 (299, 0.022424955017243866),
 (300, 0.06541867556977009),
 (301, 0.07866868132289853),
 (302, 0.1428139852200272),
 (303, 0.11979305199464946),
 (304, 0.01858409288796079),
 (305, 0.13445376799866068),
 (306, 0.04809338200514574),
 (307, 0.0979064447776707),
 (308, 0.0),
 (309, 0.17415730924332484),
 (310, 0.07437756212042423),
 (311, 0.0),
 (312, 0.1238906533021012),
 (313, 0.010423913217045038),
 (314, 0.025808491020821493),
 (315, 0.0),
 (316, 0.08951389572154368),
 (317, 0.04005551020725377),
 (318, 0.19182230688281934),
 (319, 0.02267512161790004),
 (320, 0.017303468493582226),
 (321, 0.03054044240047009),
 (322, 0.0700882246357741),
 (323, 0.10084626149563478),
 (324, 0.10467615354986062),
 (325, 0.016834621675675482),
 (326, 0.12468283384023092),
 (327, 0.10266459423639845),
 (328, 0.035498355256648746),
 (329, 0.026674838717939867),
 (330, 0.07652764821891074),
 (331, 0.08474055728984814),
 (332, 0.018319772326554337),
 (333, 0.021774817728178283),
 (334, 0.15293362041446346),
 (335, 0.0),
 (336, 0.0),
 (337, 0.010632508151830204),
 (338, 0.021530886296301118),
 (339, 0.02946442510264468),
 (340, 0.0),
 (341, 0.020767833514212724),
 (342, 0.011948245768325256),
 (343, 0.009536746594659161),
 (344, 0.20675540390454),
 (345, 0.015542921836058245),
 (346, 0.03902659506471766),
 (347, 0.06681045925540752),
 (348, 0.09014973218560086),
 (349, 0.05914734917065386),
 (350, 0.06206857320564754),
 (351, 0.0),
 (352, 0.020059585724360268),
 (353, 0.07843565693314272),
 (354, 0.16337845332530374),
 (355, 0.07161075491687474),
 (356, 0.0),
 (357, 0.1459525808785892),
 (358, 0.07561631141753603),
 (359, 0.029397384230560795),
 (360, 0.047796293241950796),
 (361, 0.018072383204619496),
 (362, 0.11362722122094872),
 (363, 0.09791273187403503),
 (364, 0.07999692625971765),
 (365, 0.0891233745026412),
 (366, 0.10941777035919222),
 (367, 0.0),
 (368, 0.02115842407200956),
 (369, 0.060039300152930415),
 (370, 0.017971540540139944),
 (371, 0.05755407693373189),
 (372, 0.021668631362692693),
 (373, 0.09754449459555777),
 (374, 0.13107651944057502),
 (375, 0.0),
 (376, 0.06829903941402894),
 (377, 0.09132921952528268),
 (378, 0.0),
 (379, 0.02781406274224919),
 (380, 0.015333681815045101),
 (381, 0.06113178628791212),
 (382, 0.017572862308732076),
 (383, 0.024712941476041382),
 (384, 0.018015801292409934),
 (385, 0.1178980615083171),
 (386, 0.06468143253238315),
 (387, 0.1390419059870689),
 (388, 0.0),
 (389, 0.06671644037106779),
 (390, 0.0),
 (391, 0.0),
 (392, 0.05762086381548707),
 (393, 0.02266096293926825),
 (394, 0.008448763927099017),
 (395, 0.02297481006625077),
 (396, 0.07136276113078666),
 (397, 0.1530551446766823),
 (398, 0.06039873575147915),
 (399, 0.0),
 (400, 0.08996912406728536),
 (401, 0.015459465622161536),
 (402, 0.10135299399598713),
 (403, 0.0),
 (404, 0.016763442237401817),
 (405, 0.0),
 (406, 0.05021880312673623),
 (407, 0.16041182196659062),
 (408, 0.0),
 (409, 0.1343973311768824),
 (410, 0.12508513698245888),
 (411, 0.02329035016031528),
 (412, 0.019872703940133213),
 (413, 0.011056735115042383),
 (414, 0.025480338679592467),
 (415, 0.0089604367821904),
 (416, 0.0824612198578452),
 (417, 0.01902896010686717),
 (418, 0.07025002832914887),
 (419, 0.021636698437203145),
 (420, 0.12822981990037824),
 (421, 0.0999877199669616),
 (422, 0.08642894687915843),
 (423, 0.0635519690782283),
 (424, 0.028830240654024085),
 (425, 0.04335826491498011),
 (426, 0.04706590154362337),
 (427, 0.0522373263993224),
 (428, 0.0),
 (429, 0.08982750671022352),
 (430, 0.00875634332679306),
 (431, 0.0992354177657422),
 (432, 0.10228551050235933),
 (433, 0.0),
 (434, 0.12307492189941618),
 (435, 0.01758928833928951),
 (436, 0.020281245334279798),
 (437, 0.1033826953037451),
 (438, 0.130281708532021),
 (439, 0.08988894455657523),
 (440, 0.09005001295005992),
 (441, 0.05332049434044375),
 (442, 0.08033435626539932),
 (443, 0.045977952103493924),
 (444, 0.061398875647666676),
 (445, 0.023007092325074995),
 (446, 0.023049037833599993),
 (447, 0.06523041320455897),
 (448, 0.01915362558614925),
 (449, 0.0),
 (450, 0.04542765998492866),
 (451, 0.0),
 (452, 0.0),
 (453, 0.05261953990010256),
 (454, 0.01317087876205714),
 (455, 0.0),
 (456, 0.0),
 (457, 0.048593102089385304),
 (458, 0.07348190409223959),
 (459, 0.10354480865656568),
 (460, 0.0171880657878069),
 (461, 0.09919937023309428),
 (462, 0.08091989315700655),
 (463, 0.0035883533320389396),
 (464, 0.04757132169040053),
 (465, 0.11122764671322921),
 (466, 0.05143480653633815),
 (467, 0.05666140304625101),
 (468, 0.0),
 (469, 0.060877194204984726),
 (470, 0.10800615252570414),
 (471, 0.0),
 (472, 0.0755468596127809),
 (473, 0.0),
 (474, 0.13644383961641227),
 (475, 0.04796762686649386),
 (476, 0.16104067376144765),
 (477, 0.0),
 (478, 0.017598641856748937),
 (479, 0.05438295377092604),
 (480, 0.0),
 (481, 0.08100800937525751),
 (482, 0.13090710604063543),
 (483, 0.00581843892000093),
 (484, 0.07150547342980032),
 (485, 0.05428487095514969),
 (486, 0.06143184266443724),
 (487, 0.051616531477964966),
 (488, 0.19511819825564608),
 (489, 0.11494879598141551),
 (490, 0.06513046875777172),
 (491, 0.06401961292305569),
 (492, 0.0),
 (493, 0.0),
 (494, 0.10853661984252007),
 (495, 0.11400426236261282),
 (496, 0.046392498261486066),
 (497, 0.018252769789423258),
 (498, 0.0),
 (499, 0.011952011165403655),
 (500, 0.21057743765309012),
 (501, 0.058097069301565475),
 (502, 0.043491562429456586),
 (503, 0.02646255704581015),
 (504, 0.07276403383736725),
 (505, 0.05264856975654457),
 (506, 0.07242165076731459),
 (507, 0.06790897506872169),
 (508, 0.016265641643564675),
 (509, 0.024318094429406693),
 (510, 0.020935646634428463),
 (511, 0.13617057407600314),
 (512, 0.11784149206441577),
 (513, 0.08588206473402643),
 (514, 0.0928435169211848),
 (515, 0.11277296885857815),
 (516, 0.06868983304237651),
 (517, 0.08200947294838495),
 (518, 0.13369059478865902),
 (519, 0.0),
 (520, 0.19972624710300058),
 (521, 0.0228620664348094),
 (522, 0.08062879942666365),
 (523, 0.0),
 (524, 0.057560148077814344),
 (525, 0.06738056011305654),
 (526, 0.0),
 (527, 0.19656287691544358),
 (528, 0.06306425554305625),
 (529, 0.03499381360818396),
 (530, 0.06123118935155921),
 (531, 0.09596456280564838),
 (532, 0.021801683645525486),
 (533, 0.023175154774464087),
 (534, 0.06476148889541151),
 (535, 0.07052240553428667),
 (536, 0.08280451731096075),
 (537, 0.17008719986228352),
 (538, 0.07213921021695388),
 (539, 0.011722012964226876),
 (540, 0.08541217689607684),
 (541, 0.17990898085771034),
 (542, 0.08007284499901246),
 (543, 0.017396246144706713),
 (544, 0.1672877700938274),
 (545, 0.2639619371123496),
 (546, 0.18408910419891056),
 (547, 0.05600272988869),
 (548, 0.04133585716291763),
 (549, 0.0691101496608291),
 (550, 0.1445684727872654),
 (551, 0.2262639743141286),
 (552, 0.1920889620576415),
 (553, 0.023933399289577127),
 (554, 0.20025063706783053),
 (555, 0.015076532862248153),
 (556, 0.05144282019851702),
 (557, 0.12333680291383342),
 (558, 0.14201659839857333),
 (559, 0.024720785609384784),
 (560, 0.08563805381851426),
 (561, 0.023634261138311616),
 (562, 0.1279402426979562),
 (563, 0.01083152786792504),
 (564, 0.07352435567112062),
 (565, 0.09532519178944057),
 (566, 0.03421894679431926),
 (567, 0.0719421185191427),
 (568, 0.022970785411852147),
 (569, 0.15344079020689355),
 (570, 0.08856301637769422),
 (571, 0.0),
 (572, 0.0),
 (573, 0.018786559700050654),
 (574, 0.09772941568150427),
 (575, 0.044043586511889346),
 (576, 0.15211972188253267),
 (577, 0.015222501642298877),
 (578, 0.10307399310158656),
 (579, 0.057157891413611744),
 (580, 0.046000562607200646),
 (581, 0.06303898971663935),
 (582, 0.06572303470837207),
 (583, 0.14421330855040418),
 (584, 0.08272478073987326),
 (585, 0.0),
 (586, 0.04203701143606598),
 (587, 0.022760772453994885),
 (588, 0.1738182944100774),
 (589, 0.019099672781938637),
 (590, 0.16000267935045498),
 (591, 0.1468148574991744),
 (592, 0.0),
 (593, 0.05940546334243634),
 (594, 0.07725115117942094),
 (595, 0.07464762808145006),
 (596, 0.06546695823953794),
 (597, 0.07021576771146076),
 (598, 0.18921367782346202),
 (599, 0.02494136129371724),
 (600, 0.017050265851722604),
 (601, 0.05437622462310082),
 (602, 0.04932819154504025),
 (603, 0.0),
 (604, 0.1144539948977886),
 (605, 0.08001595368794219),
 (606, 0.1285851502948571),
 (607, 0.023066582966561253),
 (608, 0.06129105448105361),
 (609, 0.02090768582511093),
 (610, 0.04550867061591275),
 (611, 0.10266590131312461),
 (612, 0.10725981836116358),
 (613, 0.026053401473749117),
 (614, 0.0017370894470936135),
 (615, 0.09872940458571848),
 (616, 0.0807748212690039),
 (617, 0.02159225803102367),
 (618, 0.016142753550857224),
 (619, 0.020846396819831855),
 (620, 0.09797466122629746),
 (621, 0.019067312487474012),
 (622, 0.18571699439818884),
 (623, 0.053445774200822666),
 (624, 0.18925313707609975),
 (625, 0.05894189200911533),
 (626, 0.014881608648267744),
 (627, 0.12024780353669523),
 (628, 0.09840359079895453),
 (629, 0.010481255663709239),
 (630, 0.10596223905942811),
 (631, 0.07617194789896939),
 (632, 0.08054389803075192),
 (633, 0.0),
 (634, 0.23299389358170397),
 (635, 0.01073641547918824),
 (636, 0.13573542468856645),
 (637, 0.045785523306335146),
 (638, 0.14440017099395475),
 (639, 0.0),
 (640, 0.12522954271046705),
 (641, 0.06455010070487521),
 (642, 0.02817521704586765),
 (643, 0.1444555917585842),
 (644, 0.017210453378914768),
 (645, 0.09508161331593905),
 (646, 0.05179020017229585),
 (647, 0.1841081817659337),
 (648, 0.08704223712018071),
 (649, 0.10990764051155277),
 (650, 0.10850377176901972),
 (651, 0.03954864515701187),
 (652, 0.03836309816637586),
 (653, 0.02463490862737704),
 (654, 0.07845404559691257),
 (655, 0.03455547895208963),
 (656, 0.030076807297674774),
 (657, 0.024840764583155147),
 (658, 0.04223674045619745),
 (659, 0.14444516556944695),
 (660, 0.12340233502840114),
 (661, 0.015102006885841438),
 (662, 0.028443700563612766),
 (663, 0.021320163671431275),
 (664, 0.07391777683093743),
 (665, 0.08904275766583061),
 (666, 0.1589387141616799),
 (667, 0.06947573726333098),
 (668, 0.010607867311865709),
 (669, 0.0),
 (670, 0.09993168845101595),
 (671, 0.05711356172333468),
 (672, 0.09488374038474037),
 (673, 0.009489432211152974),
 (674, 0.13365875731715243),
 (675, 0.057940637804840725),
 (676, 0.0),
 (677, 0.0672128392842741),
 (678, 0.020669978441948792),
 (679, 0.0),
 (680, 0.018394279624570017),
 (681, 0.0),
 (682, 0.1265536444037226),
 (683, 0.08418288167449578),
 (684, 0.09095705260744957),
 (685, 0.007305889033771798),
 (686, 0.08143881222401984),
 (687, 0.0),
 (688, 0.042188025333763236),
 (689, 0.0839284865111645),
 (690, 0.07785800873431292),
 (691, 0.0),
 (692, 0.07151793939760116),
 (693, 0.02407593195976403),
 (694, 0.016351262734144115),
 (695, 0.03734566872286401),
 (696, 0.05237226614377158),
 (697, 0.011401692977613393),
 (698, 0.009687245558530464),
 (699, 0.12530648498478347),
 (700, 0.009099054369341325),
 (701, 0.05864096359154978),
 (702, 0.017696441246693336),
 (703, 0.12110366748083307),
 (704, 0.07347566833900478),
 (705, 0.04316045784191231)]

In [88]:
list(enumerate(similarity_scores[3]))

[(0, 0.0),
 (1, 0.0),
 (2, 0.0),
 (3, 1.0),
 (4, 0.0),
 (5, 0.11158234783062482),
 (6, 0.0),
 (7, 0.0),
 (8, 0.07439555056493442),
 (9, 0.0),
 (10, 0.0),
 (11, 0.14576203341012606),
 (12, 0.05499338389911775),
 (13, 0.0),
 (14, 0.0),
 (15, 0.0),
 (16, 0.0),
 (17, 0.042898160366533294),
 (18, 0.0),
 (19, 0.11215378957501862),
 (20, 0.0),
 (21, 0.0),
 (22, 0.024738980596645314),
 (23, 0.0),
 (24, 0.02540679568643376),
 (25, 0.12305173578602326),
 (26, 0.0),
 (27, 0.0),
 (28, 0.0),
 (29, 0.0),
 (30, 0.093810493917375),
 (31, 0.0),
 (32, 0.06859607433155815),
 (33, 0.0),
 (34, 0.07794009648081775),
 (35, 0.03771541627007571),
 (36, 0.08134518347820842),
 (37, 0.0),
 (38, 0.0),
 (39, 0.0),
 (40, 0.0),
 (41, 0.0),
 (42, 0.05477141171610637),
 (43, 0.0),
 (44, 0.05958854548495317),
 (45, 0.0),
 (46, 0.0),
 (47, 0.076840468344349),
 (48, 0.0),
 (49, 0.0),
 (50, 0.0),
 (51, 0.0),
 (52, 0.0),
 (53, 0.0),
 (54, 0.06703391476616781),
 (55, 0.0),
 (56, 0.0),
 (57, 0.032452713484550345),
 (58, 0.0),
 (59, 0.04088609762466318),
 (60, 0.0),
 (61, 0.0),
 (62, 0.0),
 (63, 0.0),
 (64, 0.0),
 (65, 0.009403600445091611),
 (66, 0.0),
 (67, 0.0),
 (68, 0.009395542951309748),
 (69, 0.0),
 (70, 0.0),
 (71, 0.0),
 (72, 0.0),
 (73, 0.009450865566518299),
 (74, 0.0),
 (75, 0.0),
 (76, 0.0),
 (77, 0.0),
 (78, 0.0),
 (79, 0.0),
 (80, 0.013915259496356153),
 (81, 0.0),
 (82, 0.08376124843633354),
 (83, 0.0),
 (84, 0.0),
 (85, 0.0),
 (86, 0.0),
 (87, 0.1313547114095477),
 (88, 0.17154710645770874),
 (89, 0.0),
 (90, 0.0),
 (91, 0.0),
 (92, 0.0),
 (93, 0.0),
 (94, 0.0),
 (95, 0.0),
 (96, 0.0),
 (97, 0.0),
 (98, 0.0),
 (99, 0.0),
 (100, 0.04600351871369838),
 (101, 0.0),
 (102, 0.05049881954993827),
 (103, 0.0),
 (104, 0.0),
 (105, 0.0),
 (106, 0.0),
 (107, 0.0),
 (108, 0.0),
 (109, 0.05043018494335035),
 (110, 0.0),
 (111, 0.10676555331514853),
 (112, 0.0571029666194624),
 (113, 0.010661060422938726),
 (114, 0.0),
 (115, 0.0),
 (116, 0.08575255432153871),
 (117, 0.06960267547118557),
 (118, 0.009128887834672379),
 (119, 0.0),
 (120, 0.0),
 (121, 0.05441552498722499),
 (122, 0.0),
 (123, 0.03913302609057724),
 (124, 0.0),
 (125, 0.0),
 (126, 0.0),
 (127, 0.0),
 (128, 0.0),
 (129, 0.0),
 (130, 0.014406971156844837),
 (131, 0.0),
 (132, 0.0),
 (133, 0.12004349302187033),
 (134, 0.0),
 (135, 0.0),
 (136, 0.0),
 (137, 0.0),
 (138, 0.0),
 (139, 0.0),
 (140, 0.0),
 (141, 0.027247697908977457),
 (142, 0.0),
 (143, 0.0),
 (144, 0.0),
 (145, 0.0),
 (146, 0.0),
 (147, 0.0),
 (148, 0.0),
 (149, 0.0),
 (150, 0.1233401553898893),
 (151, 0.0),
 (152, 0.0),
 (153, 0.009564957099304265),
 (154, 0.0),
 (155, 0.0),
 (156, 0.0399010313771838),
 (157, 0.14343388988137237),
 (158, 0.0),
 (159, 0.0),
 (160, 0.045600183568468455),
 (161, 0.06717620552156744),
 (162, 0.10647205062933278),
 (163, 0.0),
 (164, 0.0),
 (165, 0.0),
 (166, 0.0),
 (167, 0.0),
 (168, 0.09259923557718977),
 (169, 0.06387072323530389),
 (170, 0.0),
 (171, 0.0),
 (172, 0.0),
 (173, 0.0),
 (174, 0.0),
 (175, 0.0),
 (176, 0.0),
 (177, 0.0),
 (178, 0.0),
 (179, 0.0),
 (180, 0.0),
 (181, 0.04320058391383851),
 (182, 0.0),
 (183, 0.019059074261426473),
 (184, 0.07076543419999186),
 (185, 0.0),
 (186, 0.0),
 (187, 0.00955608414208016),
 (188, 0.0),
 (189, 0.0),
 (190, 0.0),
 (191, 0.0),
 (192, 0.0),
 (193, 0.0),
 (194, 0.0),
 (195, 0.0),
 (196, 0.0),
 (197, 0.12883477701962698),
 (198, 0.06979596696834257),
 (199, 0.0),
 (200, 0.0),
 (201, 0.0),
 (202, 0.0),
 (203, 0.0),
 (204, 0.0),
 (205, 0.0),
 (206, 0.06184529377657552),
 (207, 0.0),
 (208, 0.0),
 (209, 0.0),
 (210, 0.0),
 (211, 0.07890728657735743),
 (212, 0.0),
 (213, 0.0),
 (214, 0.03151185750377314),
 (215, 0.09868721801057619),
 (216, 0.09922711265929088),
 (217, 0.0),
 (218, 0.11398462926224803),
 (219, 0.0),
 (220, 0.0),
 (221, 0.0),
 (222, 0.0),
 (223, 0.0),
 (224, 0.0),
 (225, 0.0),
 (226, 0.007319785662612407),
 (227, 0.0),
 (228, 0.08500151483453498),
 (229, 0.04228386081097231),
 (230, 0.04304939335013067),
 (231, 0.05235279711652995),
 (232, 0.0),
 (233, 0.08146719854893646),
 (234, 0.07937953259881222),
 (235, 0.1051354491423606),
 (236, 0.0),
 (237, 0.0),
 (238, 0.0),
 (239, 0.0),
 (240, 0.0),
 (241, 0.14887459750526022),
 (242, 0.10506085853407607),
 (243, 0.0),
 (244, 0.09415231371547175),
 (245, 0.0),
 (246, 0.0),
 (247, 0.0),
 (248, 0.0),
 (249, 0.0),
 (250, 0.0),
 (251, 0.03707166133396149),
 (252, 0.0),
 (253, 0.08914330135680404),
 (254, 0.0),
 (255, 0.055455464473211376),
 (256, 0.0),
 (257, 0.0),
 (258, 0.0),
 (259, 0.0),
 (260, 0.0633271394504106),
 (261, 0.0),
 (262, 0.04125739605117268),
 (263, 0.0),
 (264, 0.0),
 (265, 0.048110930245953996),
 (266, 0.008458783949162512),
 (267, 0.0),
 (268, 0.0),
 (269, 0.0),
 (270, 0.04757652016325853),
 (271, 0.0),
 (272, 0.0),
 (273, 0.10491215236112195),
 (274, 0.0),
 (275, 0.0),
 (276, 0.0),
 (277, 0.0),
 (278, 0.0),
 (279, 0.0),
 (280, 0.0),
 (281, 0.0),
 (282, 0.0),
 (283, 0.0),
 (284, 0.039204500461028156),
 (285, 0.0),
 (286, 0.04991736252318974),
 (287, 0.0),
 (288, 0.0),
 (289, 0.0),
 (290, 0.0),
 (291, 0.0),
 (292, 0.09514653109436726),
 (293, 0.028150886305252643),
 (294, 0.0),
 (295, 0.0),
 (296, 0.0),
 (297, 0.0),
 (298, 0.11887354688489958),
 (299, 0.0),
 (300, 0.0),
 (301, 0.049073219574724526),
 (302, 0.0),
 (303, 0.0),
 (304, 0.0),
 (305, 0.0),
 (306, 0.11840183894284174),
 (307, 0.0860847808896308),
 (308, 0.0),
 (309, 0.0),
 (310, 0.0),
 (311, 0.07837604400307331),
 (312, 0.061189329076939865),
 (313, 0.0),
 (314, 0.0),
 (315, 0.0),
 (316, 0.0),
 (317, 0.0),
 (318, 0.02930631269195515),
 (319, 0.0),
 (320, 0.0),
 (321, 0.0),
 (322, 0.14284952400575568),
 (323, 0.06750413993339342),
 (324, 0.0),
 (325, 0.0),
 (326, 0.0),
 (327, 0.03625534500463589),
 (328, 0.039241032719243576),
 (329, 0.0),
 (330, 0.0),
 (331, 0.0),
 (332, 0.011839204138619533),
 (333, 0.0),
 (334, 0.0),
 (335, 0.0),
 (336, 0.05619894092412585),
 (337, 0.0801650284274313),
 (338, 0.0),
 (339, 0.057124401559015436),
 (340, 0.0),
 (341, 0.0),
 (342, 0.0),
 (343, 0.0),
 (344, 0.0),
 (345, 0.0),
 (346, 0.0),
 (347, 0.0),
 (348, 0.08985298600473585),
 (349, 0.0),
 (350, 0.0),
 (351, 0.0),
 (352, 0.0),
 (353, 0.0),
 (354, 0.0),
 (355, 0.0),
 (356, 0.0),
 (357, 0.0),
 (358, 0.1717379494369234),
 (359, 0.0),
 (360, 0.13237923547629468),
 (361, 0.009343462580949763),
 (362, 0.0),
 (363, 0.043854914757673356),
 (364, 0.0),
 (365, 0.0),
 (366, 0.0),
 (367, 0.0),
 (368, 0.06077195899473463),
 (369, 0.0),
 (370, 0.09678465310027684),
 (371, 0.0),
 (372, 0.032949208619683035),
 (373, 0.01218133384264303),
 (374, 0.0),
 (375, 0.0),
 (376, 0.09655284925497716),
 (377, 0.0),
 (378, 0.18082023336625944),
 (379, 0.0),
 (380, 0.03096698371317546),
 (381, 0.0),
 (382, 0.0),
 (383, 0.0),
 (384, 0.13583222341573237),
 (385, 0.0),
 (386, 0.11320984133777257),
 (387, 0.0),
 (388, 0.0),
 (389, 0.19281549158555333),
 (390, 0.12950201134373315),
 (391, 0.0),
 (392, 0.053856097428248303),
 (393, 0.0),
 (394, 0.0),
 (395, 0.0),
 (396, 0.11529596026942476),
 (397, 0.13520967471697068),
 (398, 0.035301028959338246),
 (399, 0.05833565431482608),
 (400, 0.0),
 (401, 0.0),
 (402, 0.0827015858993283),
 (403, 0.0),
 (404, 0.0),
 (405, 0.0),
 (406, 0.0),
 (407, 0.0),
 (408, 0.0),
 (409, 0.0),
 (410, 0.10434074574032465),
 (411, 0.0),
 (412, 0.0),
 (413, 0.08002899534791355),
 (414, 0.0),
 (415, 0.0),
 (416, 0.0),
 (417, 0.16338132022337626),
 (418, 0.0),
 (419, 0.0),
 (420, 0.17982397105535214),
 (421, 0.0),
 (422, 0.0),
 (423, 0.0),
 (424, 0.0),
 (425, 0.0),
 (426, 0.0),
 (427, 0.0),
 (428, 0.0),
 (429, 0.0),
 (430, 0.0),
 (431, 0.07149048065161706),
 (432, 0.0),
 (433, 0.0),
 (434, 0.0734366239733826),
 (435, 0.012991002077031721),
 (436, 0.0),
 (437, 0.06441866298640851),
 (438, 0.0),
 (439, 0.0),
 (440, 0.03800051401859262),
 (441, 0.0),
 (442, 0.12113803933659045),
 (443, 0.0),
 (444, 0.0),
 (445, 0.0),
 (446, 0.0),
 (447, 0.0),
 (448, 0.0),
 (449, 0.0),
 (450, 0.0),
 (451, 0.0),
 (452, 0.0),
 (453, 0.08926450294053102),
 (454, 0.0),
 (455, 0.0),
 (456, 0.0),
 (457, 0.0),
 (458, 0.018622700461793814),
 (459, 0.0),
 (460, 0.0),
 (461, 0.0),
 (462, 0.04428180870902496),
 (463, 0.06261255136145931),
 (464, 0.0),
 (465, 0.0),
 (466, 0.0453271195603814),
 (467, 0.009415951791458326),
 (468, 0.03716325297778414),
 (469, 0.0),
 (470, 0.0),
 (471, 0.0),
 (472, 0.0),
 (473, 0.0),
 (474, 0.0),
 (475, 0.0),
 (476, 0.0),
 (477, 0.0),
 (478, 0.0),
 (479, 0.0),
 (480, 0.0),
 (481, 0.0),
 (482, 0.0),
 (483, 0.04386879509185782),
 (484, 0.08001837632973935),
 (485, 0.063951106378736),
 (486, 0.0),
 (487, 0.0),
 (488, 0.0),
 (489, 0.0),
 (490, 0.06109947249538),
 (491, 0.06033541212247387),
 (492, 0.0),
 (493, 0.0),
 (494, 0.13638740566268653),
 (495, 0.0),
 (496, 0.12060139688643617),
 (497, 0.0),
 (498, 0.0),
 (499, 0.13903237199542137),
 (500, 0.07151680248259212),
 (501, 0.0),
 (502, 0.047370579678090864),
 (503, 0.0734587225804091),
 (504, 0.0),
 (505, 0.05275083031891357),
 (506, 0.0),
 (507, 0.06508571109999516),
 (508, 0.0),
 (509, 0.0),
 (510, 0.0),
 (511, 0.13186636439267943),
 (512, 0.021100990796451183),
 (513, 0.0),
 (514, 0.0),
 (515, 0.0),
 (516, 0.02328199135476908),
 (517, 0.029663536241108856),
 (518, 0.0),
 (519, 0.0),
 (520, 0.0),
 (521, 0.14774674418855002),
 (522, 0.0),
 (523, 0.0),
 (524, 0.08744401596657922),
 (525, 0.0),
 (526, 0.0),
 (527, 0.0),
 (528, 0.0681996469079587),
 (529, 0.0),
 (530, 0.06155462053944115),
 (531, 0.0),
 (532, 0.0),
 (533, 0.0),
 (534, 0.0),
 (535, 0.009383150401796091),
 (536, 0.1270720066157662),
 (537, 0.0),
 (538, 0.0),
 (539, 0.1272664459112394),
 (540, 0.0),
 (541, 0.0914457052590119),
 (542, 0.04450013529423945),
 (543, 0.0),
 (544, 0.010263625596919687),
 (545, 0.0412486637726125),
 (546, 0.0),
 (547, 0.008686061022858255),
 (548, 0.0),
 (549, 0.0),
 (550, 0.07261226436585877),
 (551, 0.0),
 (552, 0.0),
 (553, 0.21653836784507968),
 (554, 0.11565016502044552),
 (555, 0.0),
 (556, 0.010681145872843186),
 (557, 0.0),
 (558, 0.0669916964853801),
 (559, 0.0),
 (560, 0.0),
 (561, 0.0),
 (562, 0.0),
 (563, 0.0),
 (564, 0.0),
 (565, 0.06533775816690189),
 (566, 0.0),
 (567, 0.0),
 (568, 0.07274017837402949),
 (569, 0.0),
 (570, 0.060308656140929895),
 (571, 0.07154772967025397),
 (572, 0.0),
 (573, 0.0),
 (574, 0.0),
 (575, 0.0),
 (576, 0.15044464825156875),
 (577, 0.0),
 (578, 0.07894738550627468),
 (579, 0.024557416485588485),
 (580, 0.06606220517618183),
 (581, 0.0),
 (582, 0.021322136105955274),
 (583, 0.0),
 (584, 0.0),
 (585, 0.0),
 (586, 0.06338858468114907),
 (587, 0.0),
 (588, 0.0),
 (589, 0.05785882964373369),
 (590, 0.0),
 (591, 0.015278504437664011),
 (592, 0.0),
 (593, 0.07198302552465441),
 (594, 0.01012946111878529),
 (595, 0.026161192282092845),
 (596, 0.08277692280335833),
 (597, 0.09782603431769188),
 (598, 0.07587244874827476),
 (599, 0.0),
 (600, 0.011018782026219896),
 (601, 0.0),
 (602, 0.03814519194958786),
 (603, 0.0),
 (604, 0.0),
 (605, 0.0),
 (606, 0.027263291750849745),
 (607, 0.12173922436578168),
 (608, 0.04951189437140553),
 (609, 0.0),
 (610, 0.0),
 (611, 0.06999690066986258),
 (612, 0.0),
 (613, 0.0),
 (614, 0.0),
 (615, 0.09616415560011732),
 (616, 0.07840325387887231),
 (617, 0.0),
 (618, 0.0),
 (619, 0.09430429602164982),
 (620, 0.02710462287017334),
 (621, 0.0),
 (622, 0.010867013547871706),
 (623, 0.0),
 (624, 0.0),
 (625, 0.0),
 (626, 0.0),
 (627, 0.0),
 (628, 0.06194181424823768),
 (629, 0.063219714200119),
 (630, 0.0),
 (631, 0.0),
 (632, 0.0),
 (633, 0.05856948834866067),
 (634, 0.0),
 (635, 0.0),
 (636, 0.0),
 (637, 0.0),
 (638, 0.0),
 (639, 0.0),
 (640, 0.0),
 (641, 0.0),
 (642, 0.0),
 (643, 0.0),
 (644, 0.0),
 (645, 0.0),
 (646, 0.0),
 (647, 0.07223443141210496),
 (648, 0.0),
 (649, 0.0),
 (650, 0.09678654768697087),
 (651, 0.0),
 (652, 0.0),
 (653, 0.061912583629383025),
 (654, 0.0),
 (655, 0.0),
 (656, 0.0),
 (657, 0.041162599064405),
 (658, 0.0),
 (659, 0.0),
 (660, 0.05156192093870975),
 (661, 0.0),
 (662, 0.11258865421440606),
 (663, 0.0),
 (664, 0.0),
 (665, 0.0),
 (666, 0.0),
 (667, 0.0),
 (668, 0.05758505708870807),
 (669, 0.0),
 (670, 0.0),
 (671, 0.02976596702472832),
 (672, 0.0),
 (673, 0.1226514425013737),
 (674, 0.0),
 (675, 0.038470170558001074),
 (676, 0.0),
 (677, 0.0),
 (678, 0.0),
 (679, 0.0),
 (680, 0.07726780547518473),
 (681, 0.0),
 (682, 0.0),
 (683, 0.06925589110171372),
 (684, 0.07256944421508148),
 (685, 0.07672358257655341),
 (686, 0.0),
 (687, 0.0),
 (688, 0.0),
 (689, 0.0334808761131148),
 (690, 0.045741778227423535),
 (691, 0.12634132998528463),
 (692, 0.07134425338463857),
 (693, 0.10735805504053052),
 (694, 0.021134098610290405),
 (695, 0.0),
 (696, 0.0),
 (697, 0.0),
 (698, 0.0),
 (699, 0.011947819665801948),
 (700, 0.1234860763967322),
 (701, 0.10863774228275982),
 (702, 0.07624249789138256),
 (703, 0.0),
 (704, 0.0),
 (705, 0.0)]

In [89]:
sorted(list(enumerate(similarity_scores[0])), key = lambda x:x[1])

[(3, 0.0),
 (20, 0.0),
 (25, 0.0),
 (32, 0.0),
 (52, 0.0),
 (55, 0.0),
 (61, 0.0),
 (67, 0.0),
 (70, 0.0),
 (71, 0.0),
 (72, 0.0),
 (83, 0.0),
 (91, 0.0),
 (99, 0.0),
 (105, 0.0),
 (115, 0.0),
 (132, 0.0),
 (133, 0.0),
 (134, 0.0),
 (138, 0.0),
 (142, 0.0),
 (143, 0.0),
 (146, 0.0),
 (157, 0.0),
 (161, 0.0),
 (173, 0.0),
 (176, 0.0),
 (179, 0.0),
 (191, 0.0),
 (201, 0.0),
 (210, 0.0),
 (222, 0.0),
 (223, 0.0),
 (237, 0.0),
 (246, 0.0),
 (248, 0.0),
 (263, 0.0),
 (266, 0.0),
 (273, 0.0),
 (274, 0.0),
 (287, 0.0),
 (290, 0.0),
 (308, 0.0),
 (311, 0.0),
 (315, 0.0),
 (335, 0.0),
 (336, 0.0),
 (340, 0.0),
 (351, 0.0),
 (356, 0.0),
 (367, 0.0),
 (375, 0.0),
 (378, 0.0),
 (388, 0.0),
 (390, 0.0),
 (391, 0.0),
 (399, 0.0),
 (403, 0.0),
 (405, 0.0),
 (408, 0.0),
 (428, 0.0),
 (433, 0.0),
 (449, 0.0),
 (451, 0.0),
 (452, 0.0),
 (455, 0.0),
 (456, 0.0),
 (468, 0.0),
 (471, 0.0),
 (473, 0.0),
 (477, 0.0),
 (480, 0.0),
 (492, 0.0),
 (493, 0.0),
 (498, 0.0),
 (519, 0.0),
 (523, 0.0),
 (526, 0.0),
 (571, 0.0),
 (572, 0.0),
 (585, 0.0),
 (592, 0.0),
 (603, 0.0),
 (633, 0.0),
 (639, 0.0),
 (669, 0.0),
 (676, 0.0),
 (679, 0.0),
 (681, 0.0),
 (687, 0.0),
 (691, 0.0),
 (614, 0.0017370894470936135),
 (221, 0.00272862336930817),
 (463, 0.0035883533320389396),
 (57, 0.005579638588454276),
 (483, 0.00581843892000093),
 (685, 0.007305889033771798),
 (30, 0.007680459111722776),
 (394, 0.008448763927099017),
 (89, 0.00850895140653615),
 (430, 0.00875634332679306),
 (159, 0.00882242400686552),
 (282, 0.00885998445194921),
 (415, 0.0089604367821904),
 (700, 0.009099054369341325),
 (673, 0.009489432211152974),
 (343, 0.009536746594659161),
 (698, 0.009687245558530464),
 (129, 0.010066425112509755),
 (313, 0.010423913217045038),
 (629, 0.010481255663709239),
 (668, 0.010607867311865709),
 (337, 0.010632508151830204),
 (94, 0.010689154840164533),
 (635, 0.01073641547918824),
 (563, 0.01083152786792504),
 (413, 0.011056735115042383),
 (188, 0.011116365315772406),
 (697, 0.011401692977613393),
 (199, 0.011474570339750256),
 (539, 0.011722012964226876),
 (292, 0.011778242975805127),
 (342, 0.011948245768325256),
 (499, 0.011952011165403655),
 (165, 0.012179056920074677),
 (2, 0.012208555646509366),
 (252, 0.012345246102533871),
 (62, 0.012406560213354146),
 (295, 0.012608239194211564),
 (162, 0.012814117802391826),
 (454, 0.01317087876205714),
 (78, 0.013316271087745269),
 (81, 0.013634576553468258),
 (156, 0.014112489355409683),
 (168, 0.01432863977616057),
 (278, 0.014679640011206505),
 (31, 0.01473221255132234),
 (626, 0.014881608648267744),
 (555, 0.015076532862248153),
 (661, 0.015102006885841438),
 (182, 0.015158449197584845),
 (577, 0.015222501642298877),
 (380, 0.015333681815045101),
 (401, 0.015459465622161536),
 (345, 0.015542921836058245),
 (35, 0.01556270914112474),
 (234, 0.01559751952620105),
 (116, 0.01579666260459111),
 (100, 0.016016629607635186),
 (618, 0.016142753550857224),
 (257, 0.016216682151444957),
 (508, 0.016265641643564675),
 (694, 0.016351262734144115),
 (130, 0.016719816747289874),
 (404, 0.016763442237401817),
 (325, 0.016834621675675482),
 (139, 0.016901518597837405),
 (600, 0.017050265851722604),
 (460, 0.0171880657878069),
 (644, 0.017210453378914768),
 (320, 0.017303468493582226),
 (543, 0.017396246144706713),
 (113, 0.017527779718968118),
 (382, 0.017572862308732076),
 (435, 0.01758928833928951),
 (478, 0.017598641856748937),
 (702, 0.017696441246693336),
 (370, 0.017971540540139944),
 (384, 0.018015801292409934),
 (361, 0.018072383204619496),
 (144, 0.0181287703514146),
 (37, 0.018230696811058135),
 (497, 0.018252769789423258),
 (332, 0.018319772326554337),
 (680, 0.018394279624570017),
 (304, 0.01858409288796079),
 (265, 0.018611497829688243),
 (573, 0.018786559700050654),
 (166, 0.018873932015163516),
 (417, 0.01902896010686717),
 (240, 0.019033695446023926),
 (621, 0.019067312487474012),
 (589, 0.019099672781938637),
 (448, 0.01915362558614925),
 (54, 0.019208718234636258),
 (260, 0.019598256153707194),
 (180, 0.01962921144060071),
 (294, 0.019788442258843547),
 (412, 0.019872703940133213),
 (352, 0.020059585724360268),
 (185, 0.020135489410098205),
 (284, 0.020221447157344582),
 (436, 0.020281245334279798),
 (242, 0.020321161226731627),
 (235, 0.02033558874805688),
 (247, 0.02040796206066411),
 (678, 0.020669978441948792),
 (341, 0.020767833514212724),
 (12, 0.020839782065795794),
 (619, 0.020846396819831855),
 (193, 0.020860053643757807),
 (609, 0.02090768582511093),
 (510, 0.020935646634428463),
 (111, 0.02097867986921867),
 (96, 0.02114858980511902),
 (368, 0.02115842407200956),
 (110, 0.021163446843373374),
 (279, 0.021238372796229556),
 (148, 0.021276714965680187),
 (663, 0.021320163671431275),
 (239, 0.021353685011361416),
 (338, 0.021530886296301118),
 (617, 0.02159225803102367),
 (419, 0.021636698437203145),
 (372, 0.021668631362692693),
 (98, 0.02175821065382328),
 (333, 0.021774817728178283),
 (532, 0.021801683645525486),
 (184, 0.02190023295408395),
 (299, 0.022424955017243866),
 (393, 0.02266096293926825),
 (319, 0.02267512161790004),
 (587, 0.022760772453994885),
 (521, 0.0228620664348094),
 (568, 0.022970785411852147),
 (395, 0.02297481006625077),
 (445, 0.023007092325074995),
 (446, 0.023049037833599993),
 (607, 0.023066582966561253),
 (533, 0.023175154774464087),
 (10, 0.02322418425912186),
 (411, 0.02329035016031528),
 (561, 0.023634261138311616),
 (553, 0.023933399289577127),
 (693, 0.02407593195976403),
 (140, 0.024108621631248803),
 (285, 0.024141217209915328),
 (135, 0.02428501142412964),
 (509, 0.024318094429406693),
 (220, 0.024337026385897676),
 (200, 0.024601653277066596),
 (653, 0.02463490862737704),
 (236, 0.024635927968282654),
 (383, 0.024712941476041382),
 (559, 0.024720785609384784),
 (288, 0.02482518222135733),
 (657, 0.024840764583155147),
 (599, 0.02494136129371724),
 (18, 0.025177841632809915),
 (414, 0.025480338679592467),
 (171, 0.025783211586063344),
 (95, 0.025797824097510556),
 (314, 0.025808491020821493),
 (613, 0.026053401473749117),
 (38, 0.026104653172312028),
 (76, 0.02613276804655889),
 (258, 0.026330228561191004),
 (503, 0.02646255704581015),
 (167, 0.026674838717939867),
 (329, 0.026674838717939867),
 (97, 0.02687778911799567),
 (172, 0.027418756526771074),
 (150, 0.027667475691473428),
 (5, 0.027749013024662858),
 (379, 0.02781406274224919),
 (74, 0.02806606106883051),
 (108, 0.02810009706063171),
 (141, 0.028108399645259814),
 (642, 0.02817521704586765),
 (662, 0.028443700563612766),
 (283, 0.028806369616477166),
 (145, 0.028808272598853126),
 (424, 0.028830240654024085),
 (359, 0.029397384230560795),
 (298, 0.029430847399312027),
 (339, 0.02946442510264468),
 (126, 0.02955369248311012),
 (63, 0.029845724311982225),
 (272, 0.029876534978291205),
 (656, 0.030076807297674774),
 (321, 0.03054044240047009),
 (136, 0.030678189040978528),
 (177, 0.03199916313406436),
 (8, 0.03261686350494277),
 (93, 0.03280520241000348),
 (238, 0.03349154464789058),
 (80, 0.03349456939792139),
 (127, 0.03355602562283),
 (566, 0.03421894679431926),
 (655, 0.03455547895208963),
 (209, 0.034785003361519164),
 (268, 0.03482458685305275),
 (529, 0.03499381360818396),
 (328, 0.035498355256648746),
 (233, 0.03601739518550193),
 (178, 0.03643816906953526),
 (189, 0.036498718026030004),
 (9, 0.03667590746512177),
 (224, 0.03671505063990275),
 (226, 0.03709430441334803),
 (114, 0.03734566872286401),
 (695, 0.03734566872286401),
 (124, 0.03771888280719047),
 (652, 0.03836309816637586),
 (346, 0.03902659506471766),
 (651, 0.03954864515701187),
 (163, 0.04003333547158616),
 (317, 0.04005551020725377),
 (548, 0.04133585716291763),
 (586, 0.04203701143606598),
 (688, 0.042188025333763236),
 (658, 0.04223674045619745),
 (64, 0.04279501979786338),
 (705, 0.04316045784191231),
 (425, 0.04335826491498011),
 (502, 0.043491562429456586),
 (575, 0.044043586511889346),
 (297, 0.04433882752568145),
 (53, 0.044680983219421905),
 (267, 0.04504597870526374),
 (160, 0.04515898041752436),
 (75, 0.04521795287053612),
 (34, 0.04522616573040869),
 (450, 0.04542765998492866),
 (280, 0.04549923467689111),
 (610, 0.04550867061591275),
 (637, 0.045785523306335146),
 (443, 0.045977952103493924),
 (580, 0.046000562607200646),
 (496, 0.046392498261486066),
 (249, 0.046982457315643385),
 (426, 0.04706590154362337),
 (128, 0.04734092759216691),
 (464, 0.04757132169040053),
 (106, 0.047670497142785574),
 (102, 0.04768602689229997),
 (204, 0.047717402129725514),
 (213, 0.04773328410790857),
 (360, 0.047796293241950796),
 (475, 0.04796762686649386),
 (277, 0.04799058127298857),
 (306, 0.04809338200514574),
 (259, 0.04815971759587031),
 (457, 0.048593102089385304),
 (256, 0.049300912125160704),
 (602, 0.04932819154504025),
 (154, 0.05007429159938883),
 (406, 0.05021880312673623),
 (17, 0.05100410510067514),
 (203, 0.05141892092902459),
 (466, 0.05143480653633815),
 (556, 0.05144282019851702),
 (487, 0.051616531477964966),
 (646, 0.05179020017229585),
 (59, 0.052194792200893965),
 (427, 0.0522373263993224),
 (696, 0.05237226614377158),
 (453, 0.05261953990010256),
 (505, 0.05264856975654457),
 (107, 0.05273164983675109),
 (441, 0.05332049434044375),
 (623, 0.053445774200822666),
 (4, 0.053672244225442485),
 (208, 0.053729841666378134),
 (186, 0.05400331245399732),
 (229, 0.05416091103251691),
 (485, 0.05428487095514969),
 (601, 0.05437622462310082),
 (479, 0.05438295377092604),
 (46, 0.054850498513470236),
 (45, 0.05491435163039676),
 (264, 0.055102704646119355),
 (547, 0.05600272988869),
 (175, 0.05606788035530558),
 (56, 0.056290668459108455),
 (122, 0.056554138733275305),
 (467, 0.05666140304625101),
 (41, 0.056912401804646934),
 (671, 0.05711356172333468),
 (579, 0.057157891413611744),
 (371, 0.05755407693373189),
 (524, 0.057560148077814344),
 (392, 0.05762086381548707),
 (675, 0.057940637804840725),
 (501, 0.058097069301565475),
 (103, 0.058191840680734276),
 (701, 0.05864096359154978),
 (625, 0.05894189200911533),
 (349, 0.05914734917065386),
 (207, 0.059152881703632795),
 (125, 0.059363300295016304),
 (593, 0.05940546334243634),
 (190, 0.05994663767295999),
 (147, 0.05995157134958024),
 (369, 0.060039300152930415),
 (49, 0.060160461842087495),
 (398, 0.06039873575147915),
 (291, 0.06069830203664196),
 (170, 0.06087281632872059),
 (469, 0.060877194204984726),
 (381, 0.06113178628791212),
 (530, 0.06123118935155921),
 (608, 0.06129105448105361),
 (444, 0.061398875647666676),
 (486, 0.06143184266443724),
 (23, 0.06150451339525138),
 (85, 0.06167753120046458),
 (350, 0.06206857320564754),
 (120, 0.06237453600241552),
 (581, 0.06303898971663935),
 (528, 0.06306425554305625),
 (423, 0.0635519690782283),
 (212, 0.06388401351716998),
 (491, 0.06401961292305569),
 (232, 0.06426525769208898),
 (641, 0.06455010070487521),
 (386, 0.06468143253238315),
 (534, 0.06476148889541151),
 (104, 0.06510721558252526),
 (490, 0.06513046875777172),
 (289, 0.06520605980064662),
 (447, 0.06523041320455897),
 (109, 0.06524573363186935),
 (300, 0.06541867556977009),
 (596, 0.06546695823953794),
 (582, 0.06572303470837207),
 (196, 0.06609996896203728),
 (69, 0.06615478064452682),
 (389, 0.06671644037106779),
 (347, 0.06681045925540752),
 (90, 0.06715432766232284),
 (677, 0.0672128392842741),
 (525, 0.06738056011305654),
 (51, 0.06748675491514017),
 (11, 0.06766486753662343),
 (507, 0.06790897506872169),
 (271, 0.06795352889900172),
 (241, 0.06806264765162154),
 (376, 0.06829903941402894),
 (516, 0.06868983304237651),
 (77, 0.06876130890656589),
 (549, 0.0691101496608291),
 (667, 0.06947573726333098),
 (322, 0.0700882246357741),
 (26, 0.07009814362931202),
 (597, 0.07021576771146076),
 (418, 0.07025002832914887),
 (535, 0.07052240553428667),
 (396, 0.07136276113078666),
 (484, 0.07150547342980032),
 (692, 0.07151793939760116),
 (355, 0.07161075491687474),
 (567, 0.0719421185191427),
 (538, 0.07213921021695388),
 (506, 0.07242165076731459),
 (131, 0.07258934796997447),
 (187, 0.07262017448772083),
 (504, 0.07276403383736725),
 (704, 0.07347566833900478),
 (458, 0.07348190409223959),
 (564, 0.07352435567112062),
 (664, 0.07391777683093743),
 (112, 0.07422249010392888),
 (254, 0.07423488726781508),
 (310, 0.07437756212042423),
 (227, 0.07458136399603107),
 (123, 0.07458202717929566),
 (595, 0.07464762808145006),
 (164, 0.07477661367406771),
 (472, 0.0755468596127809),
 (358, 0.07561631141753603),
 (231, 0.0757441443938586),
 (28, 0.07600327535501016),
 (631, 0.07617194789896939),
 (330, 0.07652764821891074),
 (594, 0.07725115117942094),
 (690, 0.07785800873431292),
 (158, 0.07835976130061303),
 (244, 0.07839488163675291),
 (353, 0.07843565693314272),
 (654, 0.07845404559691257),
 (22, 0.07847534327232125),
 (301, 0.07866868132289853),
 (58, 0.07877058635507732),
 (276, 0.07885279086963545),
 (33, 0.07965814289647455),
 (39, 0.07984012108659384),
 (364, 0.07999692625971765),
 (605, 0.08001595368794219),
 (542, 0.08007284499901246),
 (442, 0.08033435626539932),
 (632, 0.08054389803075192),
 (522, 0.08062879942666365),
 (616, 0.0807748212690039),
 (462, 0.08091989315700655),
 (481, 0.08100800937525751),
 (121, 0.08139488796880032),
 (686, 0.08143881222401984),
 (517, 0.08200947294838495),
 (218, 0.0820594460339464),
 (6, 0.08216491130000354),
 (416, 0.0824612198578452),
 (584, 0.08272478073987326),
 (536, 0.08280451731096075),
 (250, 0.08294512991462386),
 (15, 0.08303111691811028),
 (88, 0.08331012208964668),
 (42, 0.08354155383339157),
 (689, 0.0839284865111645),
 (683, 0.08418288167449578),
 (215, 0.08420691059370962),
 (245, 0.08422557655984436),
 (270, 0.08466191294337998),
 (43, 0.08471898090442946),
 (331, 0.08474055728984814),
 (540, 0.08541217689607684),
 (560, 0.08563805381851426),
 (513, 0.08588206473402643),
 (296, 0.08608600626732467),
 (422, 0.08642894687915843),
 (281, 0.08673968616705958),
 (648, 0.08704223712018071),
 (24, 0.08723968326958673),
 (275, 0.08781992709390865),
 (217, 0.08784690368235953),
 (44, 0.08785938150991274),
 (570, 0.08856301637769422),
 (665, 0.08904275766583061),
 (365, 0.0891233745026412),
 (316, 0.08951389572154368),
 (50, 0.08958834926611466),
 (429, 0.08982750671022352),
 (439, 0.08988894455657523),
 (198, 0.08992738703666601),
 (400, 0.08996912406728536),
 (440, 0.09005001295005992),
 (348, 0.09014973218560086),
 (684, 0.09095705260744957),
 (377, 0.09132921952528268),
 (211, 0.09203038690315052),
 (514, 0.0928435169211848),
 (155, 0.09428288870384942),
 (672, 0.09488374038474037),
 (36, 0.09495937740802216),
 (645, 0.09508161331593905),
 (565, 0.09532519178944057),
 (531, 0.09596456280564838),
 (183, 0.09673267751838878),
 (13, 0.09673734976610586),
 (228, 0.09746696979819942),
 (373, 0.09754449459555777),
 (574, 0.09772941568150427),
 (48, 0.09779122591837026),
 (307, 0.0979064447776707),
 (363, 0.09791273187403503),
 (195, 0.09794374510256892),
 (620, 0.09797466122629746),
 (628, 0.09840359079895453),
 (615, 0.09872940458571848),
 (152, 0.09898722239993361),
 (461, 0.09919937023309428),
 (431, 0.0992354177657422),
 (137, 0.09974980034668829),
 (670, 0.09993168845101595),
 (421, 0.0999877199669616),
 (323, 0.10084626149563478),
 (402, 0.10135299399598713),
 (261, 0.10174252819190155),
 (432, 0.10228551050235933),
 (1, 0.10255024829874465),
 (327, 0.10266459423639845),
 (611, 0.10266590131312461),
 (230, 0.10266993316420167),
 (578, 0.10307399310158656),
 (437, 0.1033826953037451),
 (149, 0.10341190148072846),
 (459, 0.10354480865656568),
 (194, 0.1035963528100001),
 (84, 0.1039794092420736),
 (324, 0.10467615354986062),
 (79, 0.10519138203342883),
 (630, 0.10596223905942811),
 (151, 0.10684794535545848),
 (612, 0.10725981836116358),
 (470, 0.10800615252570414),
 (205, 0.10849696385128584),
 (650, 0.10850377176901972),
 (494, 0.10853661984252007),
 (366, 0.10941777035919222),
 (73, 0.1096807501418389),
 (649, 0.10990764051155277),
 (117, 0.1103944810687539),
 (465, 0.11122764671322921),
 (16, 0.1115354275858341),
 (515, 0.11277296885857815),
 (362, 0.11362722122094872),
 (495, 0.11400426236261282),
 (604, 0.1144539948977886),
 (489, 0.11494879598141551),
 (87, 0.11661082872914152),
 (40, 0.11679968613719667),
 (19, 0.11706383185253948),
 (512, 0.11784149206441577),
 (243, 0.11784705785247843),
 (385, 0.1178980615083171),
 (255, 0.11841889291663141),
 (303, 0.11979305199464946),
 (627, 0.12024780353669523),
 (703, 0.12110366748083307),
 (101, 0.12114265984279052),
 (29, 0.12167133598776536),
 (219, 0.12177532243608828),
 (434, 0.12307492189941618),
 (557, 0.12333680291383342),
 (216, 0.12338216998991305),
 (660, 0.12340233502840114),
 (312, 0.1238906533021012),
 (326, 0.12468283384023092),
 (410, 0.12508513698245888),
 (640, 0.12522954271046705),
 (699, 0.12530648498478347),
 (286, 0.12548312467838352),
 (682, 0.1265536444037226),
 (65, 0.12680124740531368),
 (562, 0.1279402426979562),
 (420, 0.12822981990037824),
 (606, 0.1285851502948571),
 (197, 0.12871083086643306),
 (438, 0.130281708532021),
 (482, 0.13090710604063543),
 (374, 0.13107651944057502),
 (262, 0.13257638388225185),
 (206, 0.13278139031675887),
 (68, 0.13357242093379193),
 (674, 0.13365875731715243),
 (518, 0.13369059478865902),
 (14, 0.13388864701187034),
 (409, 0.1343973311768824),
 (305, 0.13445376799866068),
 (253, 0.13510607638008787),
 (636, 0.13573542468856645),
 (511, 0.13617057407600314),
 (474, 0.13644383961641227),
 (27, 0.13658680855472938),
 (7, 0.13732869060263378),
 (387, 0.1390419059870689),
 (293, 0.13974104783917973),
 (251, 0.13974513728492968),
 (153, 0.1414518615569236),
 (86, 0.1417627291694863),
 (558, 0.14201659839857333),
 (302, 0.1428139852200272),
 (21, 0.14333792815336935),
 (583, 0.14421330855040418),
 (638, 0.14440017099395475),
 (659, 0.14444516556944695),
 (643, 0.1444555917585842),
 (550, 0.1445684727872654),
 (357, 0.1459525808785892),
 (591, 0.1468148574991744),
 (192, 0.14691166711955864),
 (169, 0.1470284656227732),
 (174, 0.14909595195082756),
 (576, 0.15211972188253267),
 (225, 0.1528098402276361),
 (334, 0.15293362041446346),
 (397, 0.1530551446766823),
 (569, 0.15344079020689355),
 (119, 0.15514318804365945),
 (214, 0.15570975499937129),
 (92, 0.1585082118281064),
 (666, 0.1589387141616799),
 (590, 0.16000267935045498),
 (407, 0.16041182196659062),
 (476, 0.16104067376144765),
 (354, 0.16337845332530374),
 (269, 0.1650329228149958),
 (118, 0.165272766123669),
 (66, 0.16566734565340113),
 (544, 0.1672877700938274),
 (537, 0.17008719986228352),
 (588, 0.1738182944100774),
 (309, 0.17415730924332484),
 (541, 0.17990898085771034),
 (202, 0.18049207281616433),
 (546, 0.18408910419891056),
 (647, 0.1841081817659337),
 (622, 0.18571699439818884),
 (60, 0.18908176672188648),
 (598, 0.18921367782346202),
 (624, 0.18925313707609975),
 (318, 0.19182230688281934),
 (552, 0.1920889620576415),
 (488, 0.19511819825564608),
 (527, 0.19656287691544358),
 (520, 0.19972624710300058),
 (554, 0.20025063706783053),
 (344, 0.20675540390454),
 (500, 0.21057743765309012),
 (181, 0.22222254415660225),
 (551, 0.2262639743141286),
 (634, 0.23299389358170397),
 (82, 0.2366937434740099),
 (545, 0.2639619371123496),
 (47, 0.2702651417103732),
 (0, 0.9999999999999999)]

In [90]:
sorted(list(enumerate(similarity_scores[0])), key = lambda x:x[1], reverse=True)

[(0, 0.9999999999999999),
 (47, 0.2702651417103732),
 (545, 0.2639619371123496),
 (82, 0.2366937434740099),
 (634, 0.23299389358170397),
 (551, 0.2262639743141286),
 (181, 0.22222254415660225),
 (500, 0.21057743765309012),
 (344, 0.20675540390454),
 (554, 0.20025063706783053),
 (520, 0.19972624710300058),
 (527, 0.19656287691544358),
 (488, 0.19511819825564608),
 (552, 0.1920889620576415),
 (318, 0.19182230688281934),
 (624, 0.18925313707609975),
 (598, 0.18921367782346202),
 (60, 0.18908176672188648),
 (622, 0.18571699439818884),
 (647, 0.1841081817659337),
 (546, 0.18408910419891056),
 (202, 0.18049207281616433),
 (541, 0.17990898085771034),
 (309, 0.17415730924332484),
 (588, 0.1738182944100774),
 (537, 0.17008719986228352),
 (544, 0.1672877700938274),
 (66, 0.16566734565340113),
 (118, 0.165272766123669),
 (269, 0.1650329228149958),
 (354, 0.16337845332530374),
 (476, 0.16104067376144765),
 (407, 0.16041182196659062),
 (590, 0.16000267935045498),
 (666, 0.1589387141616799),
 (92, 0.1585082118281064),
 (214, 0.15570975499937129),
 (119, 0.15514318804365945),
 (569, 0.15344079020689355),
 (397, 0.1530551446766823),
 (334, 0.15293362041446346),
 (225, 0.1528098402276361),
 (576, 0.15211972188253267),
 (174, 0.14909595195082756),
 (169, 0.1470284656227732),
 (192, 0.14691166711955864),
 (591, 0.1468148574991744),
 (357, 0.1459525808785892),
 (550, 0.1445684727872654),
 (643, 0.1444555917585842),
 (659, 0.14444516556944695),
 (638, 0.14440017099395475),
 (583, 0.14421330855040418),
 (21, 0.14333792815336935),
 (302, 0.1428139852200272),
 (558, 0.14201659839857333),
 (86, 0.1417627291694863),
 (153, 0.1414518615569236),
 (251, 0.13974513728492968),
 (293, 0.13974104783917973),
 (387, 0.1390419059870689),
 (7, 0.13732869060263378),
 (27, 0.13658680855472938),
 (474, 0.13644383961641227),
 (511, 0.13617057407600314),
 (636, 0.13573542468856645),
 (253, 0.13510607638008787),
 (305, 0.13445376799866068),
 (409, 0.1343973311768824),
 (14, 0.13388864701187034),
 (518, 0.13369059478865902),
 (674, 0.13365875731715243),
 (68, 0.13357242093379193),
 (206, 0.13278139031675887),
 (262, 0.13257638388225185),
 (374, 0.13107651944057502),
 (482, 0.13090710604063543),
 (438, 0.130281708532021),
 (197, 0.12871083086643306),
 (606, 0.1285851502948571),
 (420, 0.12822981990037824),
 (562, 0.1279402426979562),
 (65, 0.12680124740531368),
 (682, 0.1265536444037226),
 (286, 0.12548312467838352),
 (699, 0.12530648498478347),
 (640, 0.12522954271046705),
 (410, 0.12508513698245888),
 (326, 0.12468283384023092),
 (312, 0.1238906533021012),
 (660, 0.12340233502840114),
 (216, 0.12338216998991305),
 (557, 0.12333680291383342),
 (434, 0.12307492189941618),
 (219, 0.12177532243608828),
 (29, 0.12167133598776536),
 (101, 0.12114265984279052),
 (703, 0.12110366748083307),
 (627, 0.12024780353669523),
 (303, 0.11979305199464946),
 (255, 0.11841889291663141),
 (385, 0.1178980615083171),
 (243, 0.11784705785247843),
 (512, 0.11784149206441577),
 (19, 0.11706383185253948),
 (40, 0.11679968613719667),
 (87, 0.11661082872914152),
 (489, 0.11494879598141551),
 (604, 0.1144539948977886),
 (495, 0.11400426236261282),
 (362, 0.11362722122094872),
 (515, 0.11277296885857815),
 (16, 0.1115354275858341),
 (465, 0.11122764671322921),
 (117, 0.1103944810687539),
 (649, 0.10990764051155277),
 (73, 0.1096807501418389),
 (366, 0.10941777035919222),
 (494, 0.10853661984252007),
 (650, 0.10850377176901972),
 (205, 0.10849696385128584),
 (470, 0.10800615252570414),
 (612, 0.10725981836116358),
 (151, 0.10684794535545848),
 (630, 0.10596223905942811),
 (79, 0.10519138203342883),
 (324, 0.10467615354986062),
 (84, 0.1039794092420736),
 (194, 0.1035963528100001),
 (459, 0.10354480865656568),
 (149, 0.10341190148072846),
 (437, 0.1033826953037451),
 (578, 0.10307399310158656),
 (230, 0.10266993316420167),
 (611, 0.10266590131312461),
 (327, 0.10266459423639845),
 (1, 0.10255024829874465),
 (432, 0.10228551050235933),
 (261, 0.10174252819190155),
 (402, 0.10135299399598713),
 (323, 0.10084626149563478),
 (421, 0.0999877199669616),
 (670, 0.09993168845101595),
 (137, 0.09974980034668829),
 (431, 0.0992354177657422),
 (461, 0.09919937023309428),
 (152, 0.09898722239993361),
 (615, 0.09872940458571848),
 (628, 0.09840359079895453),
 (620, 0.09797466122629746),
 (195, 0.09794374510256892),
 (363, 0.09791273187403503),
 (307, 0.0979064447776707),
 (48, 0.09779122591837026),
 (574, 0.09772941568150427),
 (373, 0.09754449459555777),
 (228, 0.09746696979819942),
 (13, 0.09673734976610586),
 (183, 0.09673267751838878),
 (531, 0.09596456280564838),
 (565, 0.09532519178944057),
 (645, 0.09508161331593905),
 (36, 0.09495937740802216),
 (672, 0.09488374038474037),
 (155, 0.09428288870384942),
 (514, 0.0928435169211848),
 (211, 0.09203038690315052),
 (377, 0.09132921952528268),
 (684, 0.09095705260744957),
 (348, 0.09014973218560086),
 (440, 0.09005001295005992),
 (400, 0.08996912406728536),
 (198, 0.08992738703666601),
 (439, 0.08988894455657523),
 (429, 0.08982750671022352),
 (50, 0.08958834926611466),
 (316, 0.08951389572154368),
 (365, 0.0891233745026412),
 (665, 0.08904275766583061),
 (570, 0.08856301637769422),
 (44, 0.08785938150991274),
 (217, 0.08784690368235953),
 (275, 0.08781992709390865),
 (24, 0.08723968326958673),
 (648, 0.08704223712018071),
 (281, 0.08673968616705958),
 (422, 0.08642894687915843),
 (296, 0.08608600626732467),
 (513, 0.08588206473402643),
 (560, 0.08563805381851426),
 (540, 0.08541217689607684),
 (331, 0.08474055728984814),
 (43, 0.08471898090442946),
 (270, 0.08466191294337998),
 (245, 0.08422557655984436),
 (215, 0.08420691059370962),
 (683, 0.08418288167449578),
 (689, 0.0839284865111645),
 (42, 0.08354155383339157),
 (88, 0.08331012208964668),
 (15, 0.08303111691811028),
 (250, 0.08294512991462386),
 (536, 0.08280451731096075),
 (584, 0.08272478073987326),
 (416, 0.0824612198578452),
 (6, 0.08216491130000354),
 (218, 0.0820594460339464),
 (517, 0.08200947294838495),
 (686, 0.08143881222401984),
 (121, 0.08139488796880032),
 (481, 0.08100800937525751),
 (462, 0.08091989315700655),
 (616, 0.0807748212690039),
 (522, 0.08062879942666365),
 (632, 0.08054389803075192),
 (442, 0.08033435626539932),
 (542, 0.08007284499901246),
 (605, 0.08001595368794219),
 (364, 0.07999692625971765),
 (39, 0.07984012108659384),
 (33, 0.07965814289647455),
 (276, 0.07885279086963545),
 (58, 0.07877058635507732),
 (301, 0.07866868132289853),
 (22, 0.07847534327232125),
 (654, 0.07845404559691257),
 (353, 0.07843565693314272),
 (244, 0.07839488163675291),
 (158, 0.07835976130061303),
 (690, 0.07785800873431292),
 (594, 0.07725115117942094),
 (330, 0.07652764821891074),
 (631, 0.07617194789896939),
 (28, 0.07600327535501016),
 (231, 0.0757441443938586),
 (358, 0.07561631141753603),
 (472, 0.0755468596127809),
 (164, 0.07477661367406771),
 (595, 0.07464762808145006),
 (123, 0.07458202717929566),
 (227, 0.07458136399603107),
 (310, 0.07437756212042423),
 (254, 0.07423488726781508),
 (112, 0.07422249010392888),
 (664, 0.07391777683093743),
 (564, 0.07352435567112062),
 (458, 0.07348190409223959),
 (704, 0.07347566833900478),
 (504, 0.07276403383736725),
 (187, 0.07262017448772083),
 (131, 0.07258934796997447),
 (506, 0.07242165076731459),
 (538, 0.07213921021695388),
 (567, 0.0719421185191427),
 (355, 0.07161075491687474),
 (692, 0.07151793939760116),
 (484, 0.07150547342980032),
 (396, 0.07136276113078666),
 (535, 0.07052240553428667),
 (418, 0.07025002832914887),
 (597, 0.07021576771146076),
 (26, 0.07009814362931202),
 (322, 0.0700882246357741),
 (667, 0.06947573726333098),
 (549, 0.0691101496608291),
 (77, 0.06876130890656589),
 (516, 0.06868983304237651),
 (376, 0.06829903941402894),
 (241, 0.06806264765162154),
 (271, 0.06795352889900172),
 (507, 0.06790897506872169),
 (11, 0.06766486753662343),
 (51, 0.06748675491514017),
 (525, 0.06738056011305654),
 (677, 0.0672128392842741),
 (90, 0.06715432766232284),
 (347, 0.06681045925540752),
 (389, 0.06671644037106779),
 (69, 0.06615478064452682),
 (196, 0.06609996896203728),
 (582, 0.06572303470837207),
 (596, 0.06546695823953794),
 (300, 0.06541867556977009),
 (109, 0.06524573363186935),
 (447, 0.06523041320455897),
 (289, 0.06520605980064662),
 (490, 0.06513046875777172),
 (104, 0.06510721558252526),
 (534, 0.06476148889541151),
 (386, 0.06468143253238315),
 (641, 0.06455010070487521),
 (232, 0.06426525769208898),
 (491, 0.06401961292305569),
 (212, 0.06388401351716998),
 (423, 0.0635519690782283),
 (528, 0.06306425554305625),
 (581, 0.06303898971663935),
 (120, 0.06237453600241552),
 (350, 0.06206857320564754),
 (85, 0.06167753120046458),
 (23, 0.06150451339525138),
 (486, 0.06143184266443724),
 (444, 0.061398875647666676),
 (608, 0.06129105448105361),
 (530, 0.06123118935155921),
 (381, 0.06113178628791212),
 (469, 0.060877194204984726),
 (170, 0.06087281632872059),
 (291, 0.06069830203664196),
 (398, 0.06039873575147915),
 (49, 0.060160461842087495),
 (369, 0.060039300152930415),
 (147, 0.05995157134958024),
 (190, 0.05994663767295999),
 (593, 0.05940546334243634),
 (125, 0.059363300295016304),
 (207, 0.059152881703632795),
 (349, 0.05914734917065386),
 (625, 0.05894189200911533),
 (701, 0.05864096359154978),
 (103, 0.058191840680734276),
 (501, 0.058097069301565475),
 (675, 0.057940637804840725),
 (392, 0.05762086381548707),
 (524, 0.057560148077814344),
 (371, 0.05755407693373189),
 (579, 0.057157891413611744),
 (671, 0.05711356172333468),
 (41, 0.056912401804646934),
 (467, 0.05666140304625101),
 (122, 0.056554138733275305),
 (56, 0.056290668459108455),
 (175, 0.05606788035530558),
 (547, 0.05600272988869),
 (264, 0.055102704646119355),
 (45, 0.05491435163039676),
 (46, 0.054850498513470236),
 (479, 0.05438295377092604),
 (601, 0.05437622462310082),
 (485, 0.05428487095514969),
 (229, 0.05416091103251691),
 (186, 0.05400331245399732),
 (208, 0.053729841666378134),
 (4, 0.053672244225442485),
 (623, 0.053445774200822666),
 (441, 0.05332049434044375),
 (107, 0.05273164983675109),
 (505, 0.05264856975654457),
 (453, 0.05261953990010256),
 (696, 0.05237226614377158),
 (427, 0.0522373263993224),
 (59, 0.052194792200893965),
 (646, 0.05179020017229585),
 (487, 0.051616531477964966),
 (556, 0.05144282019851702),
 (466, 0.05143480653633815),
 (203, 0.05141892092902459),
 (17, 0.05100410510067514),
 (406, 0.05021880312673623),
 (154, 0.05007429159938883),
 (602, 0.04932819154504025),
 (256, 0.049300912125160704),
 (457, 0.048593102089385304),
 (259, 0.04815971759587031),
 (306, 0.04809338200514574),
 (277, 0.04799058127298857),
 (475, 0.04796762686649386),
 (360, 0.047796293241950796),
 (213, 0.04773328410790857),
 (204, 0.047717402129725514),
 (102, 0.04768602689229997),
 (106, 0.047670497142785574),
 (464, 0.04757132169040053),
 (128, 0.04734092759216691),
 (426, 0.04706590154362337),
 (249, 0.046982457315643385),
 (496, 0.046392498261486066),
 (580, 0.046000562607200646),
 (443, 0.045977952103493924),
 (637, 0.045785523306335146),
 (610, 0.04550867061591275),
 (280, 0.04549923467689111),
 (450, 0.04542765998492866),
 (34, 0.04522616573040869),
 (75, 0.04521795287053612),
 (160, 0.04515898041752436),
 (267, 0.04504597870526374),
 (53, 0.044680983219421905),
 (297, 0.04433882752568145),
 (575, 0.044043586511889346),
 (502, 0.043491562429456586),
 (425, 0.04335826491498011),
 (705, 0.04316045784191231),
 (64, 0.04279501979786338),
 (658, 0.04223674045619745),
 (688, 0.042188025333763236),
 (586, 0.04203701143606598),
 (548, 0.04133585716291763),
 (317, 0.04005551020725377),
 (163, 0.04003333547158616),
 (651, 0.03954864515701187),
 (346, 0.03902659506471766),
 (652, 0.03836309816637586),
 (124, 0.03771888280719047),
 (114, 0.03734566872286401),
 (695, 0.03734566872286401),
 (226, 0.03709430441334803),
 (224, 0.03671505063990275),
 (9, 0.03667590746512177),
 (189, 0.036498718026030004),
 (178, 0.03643816906953526),
 (233, 0.03601739518550193),
 (328, 0.035498355256648746),
 (529, 0.03499381360818396),
 (268, 0.03482458685305275),
 (209, 0.034785003361519164),
 (655, 0.03455547895208963),
 (566, 0.03421894679431926),
 (127, 0.03355602562283),
 (80, 0.03349456939792139),
 (238, 0.03349154464789058),
 (93, 0.03280520241000348),
 (8, 0.03261686350494277),
 (177, 0.03199916313406436),
 (136, 0.030678189040978528),
 (321, 0.03054044240047009),
 (656, 0.030076807297674774),
 (272, 0.029876534978291205),
 (63, 0.029845724311982225),
 (126, 0.02955369248311012),
 (339, 0.02946442510264468),
 (298, 0.029430847399312027),
 (359, 0.029397384230560795),
 (424, 0.028830240654024085),
 (145, 0.028808272598853126),
 (283, 0.028806369616477166),
 (662, 0.028443700563612766),
 (642, 0.02817521704586765),
 (141, 0.028108399645259814),
 (108, 0.02810009706063171),
 (74, 0.02806606106883051),
 (379, 0.02781406274224919),
 (5, 0.027749013024662858),
 (150, 0.027667475691473428),
 (172, 0.027418756526771074),
 (97, 0.02687778911799567),
 (167, 0.026674838717939867),
 (329, 0.026674838717939867),
 (503, 0.02646255704581015),
 (258, 0.026330228561191004),
 (76, 0.02613276804655889),
 (38, 0.026104653172312028),
 (613, 0.026053401473749117),
 (314, 0.025808491020821493),
 (95, 0.025797824097510556),
 (171, 0.025783211586063344),
 (414, 0.025480338679592467),
 (18, 0.025177841632809915),
 (599, 0.02494136129371724),
 (657, 0.024840764583155147),
 (288, 0.02482518222135733),
 (559, 0.024720785609384784),
 (383, 0.024712941476041382),
 (236, 0.024635927968282654),
 (653, 0.02463490862737704),
 (200, 0.024601653277066596),
 (220, 0.024337026385897676),
 (509, 0.024318094429406693),
 (135, 0.02428501142412964),
 (285, 0.024141217209915328),
 (140, 0.024108621631248803),
 (693, 0.02407593195976403),
 (553, 0.023933399289577127),
 (561, 0.023634261138311616),
 (411, 0.02329035016031528),
 (10, 0.02322418425912186),
 (533, 0.023175154774464087),
 (607, 0.023066582966561253),
 (446, 0.023049037833599993),
 (445, 0.023007092325074995),
 (395, 0.02297481006625077),
 (568, 0.022970785411852147),
 (521, 0.0228620664348094),
 (587, 0.022760772453994885),
 (319, 0.02267512161790004),
 (393, 0.02266096293926825),
 (299, 0.022424955017243866),
 (184, 0.02190023295408395),
 (532, 0.021801683645525486),
 (333, 0.021774817728178283),
 (98, 0.02175821065382328),
 (372, 0.021668631362692693),
 (419, 0.021636698437203145),
 (617, 0.02159225803102367),
 (338, 0.021530886296301118),
 (239, 0.021353685011361416),
 (663, 0.021320163671431275),
 (148, 0.021276714965680187),
 (279, 0.021238372796229556),
 (110, 0.021163446843373374),
 (368, 0.02115842407200956),
 (96, 0.02114858980511902),
 (111, 0.02097867986921867),
 (510, 0.020935646634428463),
 (609, 0.02090768582511093),
 (193, 0.020860053643757807),
 (619, 0.020846396819831855),
 (12, 0.020839782065795794),
 (341, 0.020767833514212724),
 (678, 0.020669978441948792),
 (247, 0.02040796206066411),
 (235, 0.02033558874805688),
 (242, 0.020321161226731627),
 (436, 0.020281245334279798),
 (284, 0.020221447157344582),
 (185, 0.020135489410098205),
 (352, 0.020059585724360268),
 (412, 0.019872703940133213),
 (294, 0.019788442258843547),
 (180, 0.01962921144060071),
 (260, 0.019598256153707194),
 (54, 0.019208718234636258),
 (448, 0.01915362558614925),
 (589, 0.019099672781938637),
 (621, 0.019067312487474012),
 (240, 0.019033695446023926),
 (417, 0.01902896010686717),
 (166, 0.018873932015163516),
 (573, 0.018786559700050654),
 (265, 0.018611497829688243),
 (304, 0.01858409288796079),
 (680, 0.018394279624570017),
 (332, 0.018319772326554337),
 (497, 0.018252769789423258),
 (37, 0.018230696811058135),
 (144, 0.0181287703514146),
 (361, 0.018072383204619496),
 (384, 0.018015801292409934),
 (370, 0.017971540540139944),
 (702, 0.017696441246693336),
 (478, 0.017598641856748937),
 (435, 0.01758928833928951),
 (382, 0.017572862308732076),
 (113, 0.017527779718968118),
 (543, 0.017396246144706713),
 (320, 0.017303468493582226),
 (644, 0.017210453378914768),
 (460, 0.0171880657878069),
 (600, 0.017050265851722604),
 (139, 0.016901518597837405),
 (325, 0.016834621675675482),
 (404, 0.016763442237401817),
 (130, 0.016719816747289874),
 (694, 0.016351262734144115),
 (508, 0.016265641643564675),
 (257, 0.016216682151444957),
 (618, 0.016142753550857224),
 (100, 0.016016629607635186),
 (116, 0.01579666260459111),
 (234, 0.01559751952620105),
 (35, 0.01556270914112474),
 (345, 0.015542921836058245),
 (401, 0.015459465622161536),
 (380, 0.015333681815045101),
 (577, 0.015222501642298877),
 (182, 0.015158449197584845),
 (661, 0.015102006885841438),
 (555, 0.015076532862248153),
 (626, 0.014881608648267744),
 (31, 0.01473221255132234),
 (278, 0.014679640011206505),
 (168, 0.01432863977616057),
 (156, 0.014112489355409683),
 (81, 0.013634576553468258),
 (78, 0.013316271087745269),
 (454, 0.01317087876205714),
 (162, 0.012814117802391826),
 (295, 0.012608239194211564),
 (62, 0.012406560213354146),
 (252, 0.012345246102533871),
 (2, 0.012208555646509366),
 (165, 0.012179056920074677),
 (499, 0.011952011165403655),
 (342, 0.011948245768325256),
 (292, 0.011778242975805127),
 (539, 0.011722012964226876),
 (199, 0.011474570339750256),
 (697, 0.011401692977613393),
 (188, 0.011116365315772406),
 (413, 0.011056735115042383),
 (563, 0.01083152786792504),
 (635, 0.01073641547918824),
 (94, 0.010689154840164533),
 (337, 0.010632508151830204),
 (668, 0.010607867311865709),
 (629, 0.010481255663709239),
 (313, 0.010423913217045038),
 (129, 0.010066425112509755),
 (698, 0.009687245558530464),
 (343, 0.009536746594659161),
 (673, 0.009489432211152974),
 (700, 0.009099054369341325),
 (415, 0.0089604367821904),
 (282, 0.00885998445194921),
 (159, 0.00882242400686552),
 (430, 0.00875634332679306),
 (89, 0.00850895140653615),
 (394, 0.008448763927099017),
 (30, 0.007680459111722776),
 (685, 0.007305889033771798),
 (483, 0.00581843892000093),
 (57, 0.005579638588454276),
 (463, 0.0035883533320389396),
 (221, 0.00272862336930817),
 (614, 0.0017370894470936135),
 (3, 0.0),
 (20, 0.0),
 (25, 0.0),
 (32, 0.0),
 (52, 0.0),
 (55, 0.0),
 (61, 0.0),
 (67, 0.0),
 (70, 0.0),
 (71, 0.0),
 (72, 0.0),
 (83, 0.0),
 (91, 0.0),
 (99, 0.0),
 (105, 0.0),
 (115, 0.0),
 (132, 0.0),
 (133, 0.0),
 (134, 0.0),
 (138, 0.0),
 (142, 0.0),
 (143, 0.0),
 (146, 0.0),
 (157, 0.0),
 (161, 0.0),
 (173, 0.0),
 (176, 0.0),
 (179, 0.0),
 (191, 0.0),
 (201, 0.0),
 (210, 0.0),
 (222, 0.0),
 (223, 0.0),
 (237, 0.0),
 (246, 0.0),
 (248, 0.0),
 (263, 0.0),
 (266, 0.0),
 (273, 0.0),
 (274, 0.0),
 (287, 0.0),
 (290, 0.0),
 (308, 0.0),
 (311, 0.0),
 (315, 0.0),
 (335, 0.0),
 (336, 0.0),
 (340, 0.0),
 (351, 0.0),
 (356, 0.0),
 (367, 0.0),
 (375, 0.0),
 (378, 0.0),
 (388, 0.0),
 (390, 0.0),
 (391, 0.0),
 (399, 0.0),
 (403, 0.0),
 (405, 0.0),
 (408, 0.0),
 (428, 0.0),
 (433, 0.0),
 (449, 0.0),
 (451, 0.0),
 (452, 0.0),
 (455, 0.0),
 (456, 0.0),
 (468, 0.0),
 (471, 0.0),
 (473, 0.0),
 (477, 0.0),
 (480, 0.0),
 (492, 0.0),
 (493, 0.0),
 (498, 0.0),
 (519, 0.0),
 (523, 0.0),
 (526, 0.0),
 (571, 0.0),
 (572, 0.0),
 (585, 0.0),
 (592, 0.0),
 (603, 0.0),
 (633, 0.0),
 (639, 0.0),
 (669, 0.0),
 (676, 0.0),
 (679, 0.0),
 (681, 0.0),
 (687, 0.0),
 (691, 0.0)]

In [93]:
sorted(list(enumerate(similarity_scores[0])), key = lambda x:x[1], reverse=True)[1:7]

[(47, 0.2702651417103732),
 (545, 0.2639619371123496),
 (82, 0.2366937434740099),
 (634, 0.23299389358170397),
 (551, 0.2262639743141286),
 (181, 0.22222254415660225)]

In [94]:
def recommend(book_name):
  # fetch index
  index = np.where(pt.index== book_name)[0][0]
  similar_items = sorted(list(enumerate(similarity_scores[0])), key = lambda x:x[1], reverse=True)[1:7]

  for i in similar_items:
    print(i[0])

In [95]:
recommend('1984')

47
545
82
634
551
181

In [96]:
def recommend(book_name):
  # fetch index
  index = np.where(pt.index== book_name)[0][0]
  similar_items = sorted(list(enumerate(similarity_scores[index])), key = lambda x:x[1], reverse=True)[1:7]

  for i in similar_items:
    print(i[0])

In [97]:
recommend('4 Blondes')

553
389
378
420
358
88

In [98]:
def recommend(book_name):
  # fetch index
  index = np.where(pt.index== book_name)[0][0]
  similar_items = sorted(list(enumerate(similarity_scores[index])), key = lambda x:x[1], reverse=True)[1:7]

  for i in similar_items:
    print(pt.index[i[0]])

In [99]:
recommend('1984')

Animal Farm
The Handmaid's Tale
Brave New World
The Vampire Lestat (Vampire Chronicles, Book II)
The Hours : A Novel
Fahrenheit 451

In [100]:
recommend('Harry Potter and the Chamber of Secrets (Book 2)')

Harry Potter and the Prisoner of Azkaban (Book 3)
Harry Potter and the Goblet of Fire (Book 4)
Harry Potter and the Sorcerer's Stone (Harry Potter (Paperback))
Harry Potter and the Sorcerer's Stone (Book 1)
Harry Potter and the Order of the Phoenix (Book 5)
Charlotte's Web (Trophy Newbery)

In [101]:
import pickle
pickle.dump(popular_df, open('popularbooks.pkl', 'wb'))

In [102]:
def recommend(book_name):
  # fetch index
  index = np.where(pt.index== book_name)[0][0]
  similar_items = sorted(list(enumerate(similarity_scores[index])), key = lambda x:x[1], reverse=True)[1:7]

  for i in similar_items:
    print(books[books['Book-Title'] == pt.index[i[0]]])

In [103]:
recommend('Harry Potter and the Chamber of Secrets (Book 2)')

             ISBN                                         Book-Title  \
3839   0439136350  Harry Potter and the Prisoner of Azkaban (Book 3)
6330   0439136369  Harry Potter and the Prisoner of Azkaban (Book 3)
85245  0786222743  Harry Potter and the Prisoner of Azkaban (Book 3)

         Book-Author Year-Of-Publication        Publisher  \
3839   J. K. Rowling                1999       Scholastic
6330   J. K. Rowling                2001       Scholastic
85245  J. K. Rowling                2000  Thorndike Press

                                             Image-URL-S  \
3839   http://images.amazon.com/images/P/0439136350.0...
6330   http://images.amazon.com/images/P/0439136369.0...
85245  http://images.amazon.com/images/P/0786222743.0...

                                             Image-URL-M  \
3839   http://images.amazon.com/images/P/0439136350.0...
6330   http://images.amazon.com/images/P/0439136369.0...
85245  http://images.amazon.com/images/P/0786222743.0...

                                             Image-URL-L
3839   http://images.amazon.com/images/P/0439136350.0...
6330   http://images.amazon.com/images/P/0439136369.0...
85245  http://images.amazon.com/images/P/0786222743.0...
            ISBN                                    Book-Title    Book-Author  \
5431  0439139597  Harry Potter and the Goblet of Fire (Book 4)  J. K. Rowling
6932  0439139600  Harry Potter and the Goblet of Fire (Book 4)  J. K. Rowling

     Year-Of-Publication              Publisher  \
5431                2000             Scholastic
6932                2002  Scholastic Paperbacks

                                            Image-URL-S  \
5431  http://images.amazon.com/images/P/0439139597.0...
6932  http://images.amazon.com/images/P/0439139600.0...

                                            Image-URL-M  \
5431  http://images.amazon.com/images/P/0439139597.0...
6932  http://images.amazon.com/images/P/0439139600.0...

                                            Image-URL-L
5431  http://images.amazon.com/images/P/0439139597.0...
6932  http://images.amazon.com/images/P/0439139600.0...
             ISBN                                         Book-Title  \
2143   059035342X  Harry Potter and the Sorcerer's Stone (Harry P...
77384  059035342x  Harry Potter and the Sorcerer's Stone (Harry P...

         Book-Author Year-Of-Publication               Publisher  \
2143   J. K. Rowling                1999  Arthur A. Levine Books
77384  J. K. Rowling                1999  Arthur A. Levine Books

                                             Image-URL-S  \
2143   http://images.amazon.com/images/P/059035342X.0...
77384  http://images.amazon.com/images/P/059035342X.0...

                                             Image-URL-M  \
2143   http://images.amazon.com/images/P/059035342X.0...
77384  http://images.amazon.com/images/P/059035342X.0...

                                             Image-URL-L
2143   http://images.amazon.com/images/P/059035342X.0...
77384  http://images.amazon.com/images/P/059035342X.0...
              ISBN                                      Book-Title  \
2809    0590353403  Harry Potter and the Sorcerer's Stone (Book 1)
9026    043936213X  Harry Potter and the Sorcerer's Stone (Book 1)
55784   043920352X  Harry Potter and the Sorcerer's Stone (Book 1)
181530  043936213x  Harry Potter and the Sorcerer's Stone (Book 1)

          Book-Author Year-Of-Publication   Publisher  \
2809    J. K. Rowling                1998  Scholastic
9026    J. K. Rowling                2001  Scholastic
55784   J. K. Rowling                2000  Scholastic
181530  J. K. Rowling                2001  Scholastic

                                              Image-URL-S  \
2809    http://images.amazon.com/images/P/0590353403.0...
9026    http://images.amazon.com/images/P/043936213X.0...
55784   http://images.amazon.com/images/P/043920352X.0...
181530  http://images.amazon.com/images/P/043936213X.0...

                                              Image-URL-M  \
2809    http://images.amazon.com/images/P/0590353403.0...
9026    http://images.amazon.com/images/P/043936213X.0...
55784   http://images.amazon.com/images/P/043920352X.0...
181530  http://images.amazon.com/images/P/043936213X.0...

                                              Image-URL-L
2809    http://images.amazon.com/images/P/0590353403.0...
9026    http://images.amazon.com/images/P/043936213X.0...
55784   http://images.amazon.com/images/P/043920352X.0...
181530  http://images.amazon.com/images/P/043936213X.0...
              ISBN                                         Book-Title  \
5506    043935806X  Harry Potter and the Order of the Phoenix (Boo...
86390   0439567610  Harry Potter and the Order of the Phoenix (Boo...
92761   0439358078  Harry Potter and the Order of the Phoenix (Boo...
203712  043935806x  Harry Potter and the Order of the Phoenix (Boo...

          Book-Author Year-Of-Publication              Publisher  \
5506    J. K. Rowling                2003             Scholastic
86390   J. K. Rowling                2003             Scholastic
92761   J. K. Rowling                2004  Scholastic Paperbacks
203712  J. K. Rowling                2003             Scholastic

                                              Image-URL-S  \
5506    http://images.amazon.com/images/P/043935806X.0...
86390   http://images.amazon.com/images/P/0439567610.0...
92761   http://images.amazon.com/images/P/0439358078.0...
203712  http://images.amazon.com/images/P/043935806X.0...

                                              Image-URL-M  \
5506    http://images.amazon.com/images/P/043935806X.0...
86390   http://images.amazon.com/images/P/0439567610.0...
92761   http://images.amazon.com/images/P/0439358078.0...
203712  http://images.amazon.com/images/P/043935806X.0...

                                              Image-URL-L
5506    http://images.amazon.com/images/P/043935806X.0...
86390   http://images.amazon.com/images/P/0439567610.0...
92761   http://images.amazon.com/images/P/0439358078.0...
203712  http://images.amazon.com/images/P/043935806X.0...
            ISBN                        Book-Title  Book-Author  \
3847  0064400557  Charlotte's Web (Trophy Newbery)  E. B. White

     Year-Of-Publication     Publisher  \
3847                1974  HarperTrophy

                                            Image-URL-S  \
3847  http://images.amazon.com/images/P/0064400557.0...

                                            Image-URL-M  \
3847  http://images.amazon.com/images/P/0064400557.0...

                                            Image-URL-L
3847  http://images.amazon.com/images/P/0064400557.0...

In [104]:
def recommend(book_name):
  # fetch index
  index = np.where(pt.index== book_name)[0][0]
  similar_items = sorted(list(enumerate(similarity_scores[index])), key = lambda x:x[1], reverse=True)[1:7]

  for i in similar_items:
    temp_df = books[books['Book-Title'] == pt.index[i[0]]]
    print(temp_df.drop_duplicates('Book-Title')['Book-Author'])

In [105]:
recommend('Harry Potter and the Chamber of Secrets (Book 2)')

3839    J. K. Rowling
Name: Book-Author, dtype: object
5431    J. K. Rowling
Name: Book-Author, dtype: object
2143    J. K. Rowling
Name: Book-Author, dtype: object
2809    J. K. Rowling
Name: Book-Author, dtype: object
5506    J. K. Rowling
Name: Book-Author, dtype: object
3847    E. B. White
Name: Book-Author, dtype: object

In [106]:
def recommend(book_name):
  # fetch index
  index = np.where(pt.index== book_name)[0][0]
  similar_items = sorted(list(enumerate(similarity_scores[index])), key = lambda x:x[1], reverse=True)[1:7]

  data = []
  for i in similar_items:
    item = []
    temp_df = books[books['Book-Title'] == pt.index[i[0]]]
    item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Title'].values))
    item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Author'].values))
    item.extend(list(temp_df.drop_duplicates('Book-Title')['Image-URL-M'].values))

    data.append(item)

  return data

In [107]:
recommend('Harry Potter and the Chamber of Secrets (Book 2)')

[['Harry Potter and the Prisoner of Azkaban (Book 3)',
  'J. K. Rowling',
  'http://images.amazon.com/images/P/0439136350.01.MZZZZZZZ.jpg'],
 ['Harry Potter and the Goblet of Fire (Book 4)',
  'J. K. Rowling',
  'http://images.amazon.com/images/P/0439139597.01.MZZZZZZZ.jpg'],
 ["Harry Potter and the Sorcerer's Stone (Harry Potter (Paperback))",
  'J. K. Rowling',
  'http://images.amazon.com/images/P/059035342X.01.MZZZZZZZ.jpg'],
 ["Harry Potter and the Sorcerer's Stone (Book 1)",
  'J. K. Rowling',
  'http://images.amazon.com/images/P/0590353403.01.MZZZZZZZ.jpg'],
 ['Harry Potter and the Order of the Phoenix (Book 5)',
  'J. K. Rowling',
  'http://images.amazon.com/images/P/043935806X.01.MZZZZZZZ.jpg'],
 ["Charlotte's Web (Trophy Newbery)",
  'E. B. White',
  'http://images.amazon.com/images/P/0064400557.01.MZZZZZZZ.jpg']]

In [108]:
pickle.dump(pt, open('pt.pkl', 'wb'))
pickle.dump(books, open('books.pkl', 'wb'))
pickle.dump(similarity_scores, open('similarityscores.pkl', 'wb'))